// boot-server.js -- GENERATED by effortless-rulebook-editor.
//
// Binds the EXTERNAL UI port (5174) immediately at container start, before
// Postgres/build even begin. Serves a placeholder boot page with a live
// SSE log tail + progress state, a "Rebuild" trigger, and once the real
// Vite dev server is confirmed reachable on the INTERNAL port (5175),
// transparently reverse-proxies everything else to it. The external port
// never changes, so a browser tab opened at t=0 just starts working once
// the build finishes -- no manual reload-until-it-works.
//
// State transitions (read from BOOT_STATE_FILE, written by
// container-entrypoint.sh): booting -> building -> ready | error, with an
// extra side-state -- awaiting-conflict-resolution -- entered before a
// GATED rebuild (pending uncommitted changes + an externally-changed
// rulebook file) and left only once POST /__boot/resolve-conflict writes a
// choice; see check_uncommitted_before_build() in container-entrypoint.sh.

const http = require('http');
const fs = require('fs');

// This process owns the one port (5174) meant to survive the whole
// container lifetime -- if it dies, the browser gets a hard connection
// reset with no indication why. A bug in any one request handler must not
// take the whole server down, so uncaught errors are logged and swallowed
// here rather than allowed to crash the process.
process.on('uncaughtException', (err) => {
  console.error('[boot-server] uncaught exception (server stays up):', err);
});
process.on('unhandledRejection', (err) => {
  console.error('[boot-server] unhandled rejection (server stays up):', err);
});

const EXTERNAL_PORT = 5174;
const INTERNAL_UI_PORT = 5175;
const STATE_FILE = process.env.BOOT_STATE_FILE || '/tmp/boot-state';
const LOG_FILE = process.env.BOOT_LOG_FILE || '/tmp/current-build.log';
const REBUILD_TRIGGER = process.env.BOOT_REBUILD_TRIGGER || '/tmp/rebuild-trigger';
const CONFLICT_CHOICE_FILE = process.env.BOOT_CONFLICT_CHOICE_FILE || '/tmp/conflict-choice';

// The rebuild OFFER (see prompt_for_rebuild() in container-entrypoint.sh).
// REBUILD_PROMPT_FILE exists only while an offer is outstanding and contains
// the epoch second it expires; the two answer files are how the app's toast
// says yes or no. Note the entrypoint deliberately does NOT change
// BOOT_STATE_FILE while asking -- the state stays 'ready' so this server keeps
// proxying the real app, and the question is asked as a toast INSIDE it rather
// than by replacing it with the boot page.
const REBUILD_PROMPT_FILE = process.env.BOOT_REBUILD_PROMPT_FILE || '/tmp/rebuild-prompt';
const REBUILD_PROMPT_CONFIRM_FILE = process.env.BOOT_REBUILD_PROMPT_CONFIRM_FILE || '/tmp/rebuild-prompt-confirm';
const REBUILD_PROMPT_DISMISS_FILE = process.env.BOOT_REBUILD_PROMPT_DISMISS_FILE || '/tmp/rebuild-prompt-dismiss';

// The effortless CLI's structured build-failure record (errors.json), copied to a
// fixed path by container-entrypoint.sh, plus the per-component health snapshot it
// writes after every build. Both are served verbatim -- the whole point is that a
// human or the portal can ask "what broke?" and "what is alive?" without shelling
// into the container to read logs.
const ERRORS_FILE = process.env.BOOT_ERRORS_FILE || '/tmp/build-errors.json';
const STATUS_FILE = process.env.BOOT_STATUS_FILE || '/tmp/boot-status.json';

// The build pipeline itself -- effortless.json's ProjectTranspilers list, which
// container-entrypoint.sh seeds onto disk BEFORE the first build starts. Serving
// it is what lets the boot page show the whole sequence, in order, with what each
// step is for, from t=0 -- instead of only revealing steps one at a time as their
// banners scroll past in the log. Read fresh on every request rather than cached:
// the pipeline is user-editable (that is the point of seeding it only-if-missing),
// and a rebuild can pick up an edited one without restarting this server.
const PIPELINE_FILE = process.env.BOOT_PIPELINE_FILE || '/app/effortless-root/effortless.json';

function readJsonFile(p) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return null;
  }
}

// Plain-language copy for each step, in the words of someone who has never heard
// of a transpiler. It lives HERE, server-side, rather than in the boot page,
// because two different front-ends render this same rail -- this page, and the
// admin portal's build monitor (a separate tool: rulebook-to-vite-admin-portal).
// Serving the words alongside the steps is what keeps the two from drifting.
// The engineer-facing text (the step's own Description, its command line) still
// rides along untouched, one disclosure down in both UIs.
const STEP_COPY = {
  rulebooktopostgres: [
    'Design the database',
    'Reads your rulebook and works out the database from it: a table for every kind of thing you described, a function for every value that gets calculated, and a view that puts them back together.',
  ],
  rulebooktorbac: [
    'Work out who can see and change what',
    'Security module. Reads the roles, users and permissions in your rulebook and writes them down as one list of who is allowed to see or change each table. Off until the Security module is switched on in the portal\'s Modules page.',
  ],
  rbactopostgrespolicies: [
    'Lock down the database to match',
    'Security module. Turns that list into database rules, so each person only sees and changes the rows their role allows -- enforced by the database itself, not just the screens. Off until the Security module is switched on.',
  ],
  chmodinitdb: [
    'Prepare the database setup script',
    'Housekeeping. Marks the setup script the previous step just wrote as runnable, so the next step can run it.',
  ],
  initdb: [
    'Update the database and load your data',
    'Applies the design above to the database and loads in the data from your rulebook. The first run after startup builds it from scratch; after that it only adds what is new -- tables, columns, and rows -- so anything you have entered here stays put.',
  ],
  rulebooktonodepostgresapi: [
    'Build the API',
    'Builds a small web service so that data can be read over the network -- by the portal, by your own code, or by anything that speaks HTTP.',
  ],
  rulebooktoviteadminportal: [
    'Build the admin portal',
    'Builds the browsable admin site: a page per table, your calculated values filled in, plus the tabs for the documents below.',
  ],
  rulebooktoexplainerdag: [
    'Add explanations for calculated values',
    'Builds the provenance graph used by the portal to explain where every calculated, lookup, and aggregated value came from.',
  ],
  rulebooktorulespeaken: [
    'Write the rules out in plain English',
    'Turns your rules into readable English sentences a person can check, in English only. The leanest of the three RuleSpeak steps.',
  ],
  rulebooktorulespeak: [
    'Write the rules out in plain language (4 languages)',
    'Turns your rules into readable sentences a person can check -- the same document in English, German, Japanese and Hindi, with a language picker. This is the default; the portal can add the remaining languages in one click.',
  ],
  rulebooktorulespeakall: [
    'Write the rules out in every language',
    'The same document in every language the renderer knows. Off by default because it is the slowest of the three; the portal turns it on when someone asks for the remaining languages.',
  ],
  rulebooktoxlsx: [
    'Export everything to an Excel workbook',
    'Writes your tables into a spreadsheet you can download and open in Excel. Enabled by default.',
  ],
  rulebooktoprogressreport: [
    'Write the progress report',
    'Delivery module. Reads the user stories, acceptance criteria and build phases in your rulebook and writes up what is done and what is left, shown under the portal\'s Progress Report tab. Off until the Delivery module is switched on.',
  ],
};

// Projected down to just what the boot page needs, and camelCased on the way out
// so the page is not reaching into effortless.json's PascalCase shape directly --
// this route is the contract, the file layout is not.
function readPipeline() {
  const cfg = readJsonFile(PIPELINE_FILE);
  const raw = (cfg && cfg.ProjectTranspilers) || [];
  return raw
    .map((t) => {
      const copy = STEP_COPY[t.Name] || [];
      return {
        name: t.Name,
        title: copy[0] || 'Missing friendly display name',
        why: copy[1] || t.Description || ('Runs: effortless ' + (t.CommandLine || t.Name)),
        relativePath: t.RelativePath,
        commandLine: t.CommandLine,
        description: t.Description,
        isDisabled: !!t.IsDisabled,
        lastVersionUsed: t.LastVersionUsed || null,
        lastUrl: t.LastUrl || null,
      };
    })
    .filter((t) => t.name);
}

// 'ready' and 'degraded' both mean "the app is up, proxy to it". They differ only
// in whether this build had failed steps -- degraded exists so that a partial
// failure is VISIBLE (via /__boot/status and the banner below) instead of silent.
function isAppServing(state) {
  return state === 'ready' || state === 'degraded';
}

function readRebuildPrompt() {
  let deadline;
  try {
    deadline = Number(fs.readFileSync(REBUILD_PROMPT_FILE, 'utf8').trim());
  } catch {
    return { pending: false, secondsLeft: 0 };
  }
  if (!Number.isFinite(deadline)) return { pending: false, secondsLeft: 0 };
  const secondsLeft = Math.max(0, deadline - Math.floor(Date.now() / 1000));
  // An expired file that the entrypoint has not cleaned up yet must not keep
  // a dead toast on screen.
  return { pending: secondsLeft > 0, secondsLeft };
}

function readState() {
  try {
    return fs.readFileSync(STATE_FILE, 'utf8').trim() || 'booting';
  } catch {
    return 'booting';
  }
}

function tailLines(n) {
  try {
    const data = fs.readFileSync(LOG_FILE, 'utf8');
    const lines = data.split('\n');
    return lines.slice(Math.max(0, lines.length - n));
  } catch {
    return [];
  }
}

const sseClients = new Set();

function broadcastLine(line) {
  for (const res of sseClients) {
    res.write(`data: ${JSON.stringify({ line })}\n\n`);
  }
}

function broadcastState(state) {
  for (const res of sseClients) {
    res.write(`event: state\ndata: ${JSON.stringify({ state })}\n\n`);
  }
}

// Watch the log file for new lines (tail -f semantics via fs.watchFile --
// portable, no extra deps, adequate for a single-writer append-only log).
let lastSize = 0;
try { lastSize = fs.existsSync(LOG_FILE) ? fs.statSync(LOG_FILE).size : 0; } catch {}
fs.watchFile(LOG_FILE, { interval: 300 }, () => {
  try {
    const stat = fs.statSync(LOG_FILE);
    if (stat.size < lastSize) lastSize = 0; // log truncated at the start of a rebuild
    const fd = fs.openSync(LOG_FILE, 'r');
    const len = stat.size - lastSize;
    if (len > 0) {
      const buf = Buffer.alloc(len);
      fs.readSync(fd, buf, 0, len, lastSize);
      buf.toString('utf8').split('\n').filter(Boolean).forEach(broadcastLine);
      lastSize = stat.size;
    }
    fs.closeSync(fd);
  } catch {}
});

let lastState = '';
setInterval(() => {
  const s = readState();
  if (s !== lastState) {
    lastState = s;
    broadcastState(s);
  }
}, 500);

// ⚠️ ESCAPING TRAP -- READ BEFORE EDITING THE PAGE BELOW.
//
// This is a JS TEMPLATE LITERAL (backticks) holding an HTML page whose <script>
// is itself JavaScript, and the whole thing lives inside a C# VERBATIM string in
// Program.cs. C# leaves a backslash alone, but the template literal then EATS it:
// a `\n` written here reaches the browser as a real newline, so `"\n"` becomes a
// string literal broken across two lines -- a SyntaxError that silently kills the
// ENTIRE inline script. When that happened, the page still rendered its static
// shell, so it looked like a blank/dead page with no log output and no state
// updates, with nothing in the container logs to explain it.
//
// Rules for anything inside this template literal:
//   - Write `\\n`, not `\n` (and `\\\\` for a literal backslash).
//   - Prefer forms with NO backslash at all: `[/]` instead of `\/` in a regex,
//     double quotes instead of an escaped apostrophe.
//   - After editing, VERIFY by running `./scripts/check.sh` in this tool's folder.
//     It extracts this template's <script> body and `node --check`s THAT, then
//     drives it through a build lifecycle under a DOM stub. `node --check
//     boot-server.js` alone does NOT catch this -- the outer file parses fine;
//     it is the string's contents that break.
const BOOT_PAGE = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Rulebook Editor -- booting</title>
<style>
  :root{color-scheme:light dark}
  body{margin:0;font-family:ui-monospace,SF Mono,Menlo,Cascadia Code,monospace;
    background:#0d1315;color:#d3dcd9;height:100vh;display:flex;flex-direction:column}
  @media (prefers-color-scheme:light){body{background:#f5f7f6;color:#1a2320}}
  header{padding:16px 22px;border-bottom:1px solid #233033;display:flex;align-items:center;gap:12px}
  @media (prefers-color-scheme:light){header{border-bottom-color:#d8dfdd}}
  h1{font-size:15px;margin:0;font-weight:650}
  .dot{width:9px;height:9px;border-radius:50%;background:#e0a03a;animation:pulse 1.4s ease-in-out infinite}
  .dot.ready{background:#4ea882;animation:none}
  .dot.error{background:#e05a3a;animation:none}
  @keyframes pulse{0%,100%{opacity:.35}50%{opacity:1}}
  .state{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#93a29d}
  .spacer{flex:1}
  button{font-family:inherit;font-size:12px;background:#141b1e;color:#d3dcd9;
    border:1px solid #233033;border-radius:6px;padding:7px 14px;cursor:pointer}
  @media (prefers-color-scheme:light){button{background:#eef2f1;color:#1a2320;border-color:#d8dfdd}}
  button:hover{filter:brightness(1.15)}
  button:disabled{opacity:.5;cursor:default}
  main{flex:1;overflow-y:auto}
  /* Two panes, one scroll container. The dashboard is a LAYER OVER the raw log,
     never a replacement for it -- when something goes wrong the unfiltered text
     has to still be one click away, so both panes always exist and the tabs just
     choose which is visible. */
  #dashPane{padding:18px 22px 26px}
  #logPane{display:none;padding:14px 22px;font-size:12.5px;line-height:1.6;white-space:pre-wrap}
  main.raw #dashPane{display:none}
  main.raw #logPane{display:block}
  .tabs{display:flex;gap:4px;margin-right:10px}
  .tab{font-family:inherit;font-size:11.5px;letter-spacing:.03em;padding:6px 12px;border-radius:6px;
    border:1px solid transparent;background:transparent;color:#93a29d;cursor:pointer}
  .tab.active{border-color:#233033;background:#141b1e;color:#d3dcd9}
  @media (prefers-color-scheme:light){.tab.active{border-color:#d8dfdd;background:#eef2f1;color:#1a2320}}
  .lead{margin:0 0 18px;font-size:12.5px;line-height:1.65;color:#93a29d;max-width:74ch}
  .lead code{color:#d3dcd9}
  @media (prefers-color-scheme:light){.lead code{color:#1a2320}}
  h2.sec{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:#93a29d;
    margin:0 0 10px;font-weight:650}
  .tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(215px,1fr));gap:10px;margin-bottom:24px}
  .tile{border:1px solid #233033;border-radius:8px;padding:12px 14px;background:rgba(255,255,255,.02)}
  @media (prefers-color-scheme:light){.tile{border-color:#d8dfdd;background:rgba(0,0,0,.02)}}
  .tile h3{margin:0 0 5px;font-size:12.5px;font-weight:650;display:flex;align-items:center;gap:8px}
  .tile p{margin:0;font-size:11.5px;line-height:1.5;color:#93a29d}
  .tile-version{margin-top:6px !important;font-family:ui-monospace,monospace;font-size:10.5px !important;
    color:#5f7570 !important}
  .pill{font-size:9.5px;text-transform:uppercase;letter-spacing:.06em;padding:2px 7px;
    border-radius:99px;border:1px solid;font-weight:650}
  .pill.up{color:#4ea882;border-color:#4ea882}
  .pill.down{color:#e05a3a;border-color:#e05a3a}
  .pill.unknown{color:#93a29d;border-color:#93a29d}
  /* PROGRESS BAR. Thick, lit, and striped while a step is actually in flight --
     a bar that only moves once per step reads as frozen during the 30s a
     generator takes, which is exactly when someone is staring at it. */
  .progress{height:10px;border-radius:99px;background:#182220;border:1px solid #26332f;
    overflow:hidden;margin-bottom:9px}
  @media (prefers-color-scheme:light){.progress{background:#e4eae8;border-color:#d8dfdd}}
  .progress-bar{height:100%;width:0;border-radius:99px;
    background:linear-gradient(90deg,#1f8f66,#3ddc97);
    box-shadow:0 0 16px rgba(61,220,151,.55);
    transition:width .5s cubic-bezier(.4,0,.2,1)}
  .progress-bar.active{background-image:repeating-linear-gradient(115deg,
      rgba(255,255,255,.22) 0 9px,rgba(255,255,255,0) 9px 18px),
      linear-gradient(90deg,#1f8f66,#3ddc97);
    background-size:36px 100%,100% 100%;animation:stripes .75s linear infinite}
  @keyframes stripes{to{background-position:36px 0,0 0}}
  /* A build that has already failed a step but is still going (continueOnError)
     is BOTH red and moving -- the colour says what happened, the stripes say it
     has not stopped. */
  .progress-bar.failed{background-image:linear-gradient(90deg,#a83c28,#ff6b52);
    box-shadow:0 0 16px rgba(255,107,82,.5);animation:none}
  .progress-bar.failed.active{background-image:repeating-linear-gradient(115deg,
      rgba(255,255,255,.22) 0 9px,rgba(255,255,255,0) 9px 18px),
      linear-gradient(90deg,#a83c28,#ff6b52);
    animation:stripes .75s linear infinite}
  .progress-label{font-size:12.5px;color:#93a29d;margin-bottom:16px}
  .progress-label b{color:#3ddc97;font-weight:650}
  .rail{display:flex;flex-direction:column}

  /* THE STEP RAIL. Planned / running / finished have to be tellable apart from
     across the room, not by one shade of grey: the running step is a 48px green
     arrow inside a lit-up card, finished steps are solid green discs strung on a
     solid green pipe, and planned steps are dim numbered rings on a dead pipe.
     The pipe filling in top-to-bottom IS the progress indicator. */
  .step{display:flex;gap:14px;padding:9px 12px 9px 0;border-radius:10px;
    transition:background .3s ease,opacity .3s ease}
  .step .gutter{position:relative;flex:0 0 66px;align-self:stretch;
    display:flex;align-items:center;justify-content:center;min-height:46px}
  .step .gutter::before,.step .gutter::after{content:'';position:absolute;left:50%;
    margin-left:-1.5px;width:3px;border-radius:2px;background:#2b3a36}
  .step .gutter::before{top:0;height:calc(50% - 21px)}
  .step .gutter::after{bottom:0;height:calc(50% - 21px)}
  .step.running .gutter::before{height:calc(50% - 34px)}
  .step.running .gutter::after{height:calc(50% - 34px)}
  .step:first-child .gutter::before{opacity:0}
  .step:last-child .gutter::after{opacity:0}
  .step.succeeded .gutter::before,.step.succeeded .gutter::after,
  .step.failed .gutter::before,.step.running .gutter::before{background:#3ddc97}
  @media (prefers-color-scheme:light){
    .step .gutter::before,.step .gutter::after{background:#ccd6d3}
    .step.succeeded .gutter::before,.step.succeeded .gutter::after,
    .step.failed .gutter::before,.step.running .gutter::before{background:#12a06c}
  }
  .glyph{position:relative;z-index:1;width:34px;height:34px;border-radius:50%;
    display:flex;align-items:center;justify-content:center;
    font-size:15px;line-height:1;font-weight:700;
    border:2px solid #33413d;background:#0d1315;color:#6d7d78;
    transition:width .25s ease,height .25s ease,color .25s ease}
  @media (prefers-color-scheme:light){.glyph{background:#f5f7f6;border-color:#c9d3d0;color:#7c8985}}
  .step.pending .glyph,.step.skipped .glyph{border-style:dashed}
  .step.succeeded .glyph{border-color:#3ddc97;background:#3ddc97;color:#06120d;
    box-shadow:0 0 0 5px rgba(61,220,151,.12)}
  .step.failed .glyph{border-color:#ff6b52;background:#ff6b52;color:#210704;
    box-shadow:0 0 0 5px rgba(255,107,82,.14)}
  /* The one the user asked to be unmissable. */
  .step.running .glyph{width:62px;height:62px;border:none;background:none;box-shadow:none;
    color:#3ddc97;font-size:48px;text-shadow:0 0 26px rgba(61,220,151,.7);
    animation:nudge 1.15s ease-in-out infinite}
  @keyframes nudge{0%,100%{transform:translateX(-4px);opacity:.7}50%{transform:translateX(5px);opacity:1}}
  .step .body{flex:1;min-width:0;padding:3px 0}
  .step .name{font-size:13px;font-weight:650;line-height:1.4;
    display:flex;align-items:center;gap:9px;flex-wrap:wrap}
  .step .why{font-size:12px;color:#93a29d;margin-top:4px;line-height:1.55;max-width:74ch}
  .step.pending{opacity:.5}
  .step.pending .name{font-weight:500}
  .step.skipped{opacity:.4}
  .step.running{background:linear-gradient(90deg,rgba(61,220,151,.16),rgba(61,220,151,.02) 70%);
    box-shadow:inset 0 0 0 1px rgba(61,220,151,.28)}
  .step.running .name{font-size:16.5px;color:#3ddc97}
  .step.running .why{color:#b9cbc4}
  .step.failed .name{color:#ff6b52}
  @media (prefers-color-scheme:light){
    .step.running .name{color:#0d7a52}
    .step.running .why{color:#3a4a45}
    .progress-label b{color:#0d7a52}
  }
  .chip{font-size:9.5px;text-transform:uppercase;letter-spacing:.09em;font-weight:700;
    padding:3px 9px;border-radius:99px;border:1px solid;white-space:nowrap}
  .chip.now{color:#06120d;background:#3ddc97;border-color:#3ddc97;
    animation:blink 1.15s ease-in-out infinite}
  @keyframes blink{0%,100%{opacity:.6}50%{opacity:1}}
  .chip.off{color:#93a29d;border-color:#3a4844}
  .chip.bad{color:#ff6b52;border-color:#ff6b52}
  .step .err{margin-top:8px;padding:9px 11px;border:1px solid #e05a3a;border-radius:6px;
    background:rgba(224,90,58,.08);font-size:11.5px;line-height:1.55;white-space:pre-wrap}
  .step details{margin-top:7px}
  .step summary{font-size:11px;color:#93a29d;cursor:pointer;letter-spacing:.02em}
  .step details pre{margin:6px 0 0;font-size:11px;line-height:1.5;white-space:pre-wrap;
    color:#93a29d;max-height:280px;overflow:auto}
  .linkish{background:none;border:none;padding:0;font-family:inherit;font-size:11px;
    color:#93a29d;text-decoration:underline;cursor:pointer}
  .hint{padding:10px 22px;font-size:12px;color:#93a29d;border-top:1px solid #233033}
  @media (prefers-color-scheme:light){.hint{border-top-color:#d8dfdd}}
  .dot.conflict{background:#e0a03a;animation:none}
  .conflict-panel{display:none;flex-direction:column;gap:10px;margin:14px 22px;padding:16px 18px;
    border:1px solid #e0a03a;border-radius:8px;background:rgba(224,160,58,.08)}
  .conflict-panel.show{display:flex}
  .conflict-panel h2{margin:0;font-size:13px;font-weight:650;color:#e0a03a}
  .conflict-panel p{margin:0;font-size:12.5px;line-height:1.6;color:#d3dcd9}
  @media (prefers-color-scheme:light){.conflict-panel p{color:#1a2320}}
  .conflict-choices{display:flex;gap:10px;flex-wrap:wrap;margin-top:4px}
  .conflict-choices button{padding:9px 14px}
  .conflict-choices button.recommended{border-color:#4ea882}
  .conflict-choices button.danger{border-color:#e05a3a}
  .dot.degraded{background:#e0a03a;animation:none}
  .fail-panel{display:none;flex-direction:column;gap:8px;margin:14px 22px;padding:16px 18px;
    border:1px solid #e05a3a;border-radius:8px;background:rgba(224,90,58,.08)}
  .fail-panel.show{display:flex}
  .fail-panel h2{margin:0;font-size:13px;font-weight:650;color:#e05a3a}
  .fail-panel p{margin:0;font-size:12.5px;line-height:1.6}
  .fail-step{padding:8px 0;border-top:1px solid rgba(224,90,58,.3)}
  .fail-step b{color:#e05a3a}
  .fail-step pre{margin:4px 0 0;font-size:11.5px;line-height:1.5;white-space:pre-wrap;opacity:.9}
  .fail-links{font-size:12px;opacity:.85}
</style>
</head>
<body>
<header>
  <span class="dot" id="dot"></span>
  <h1>effortless-rulebook-editor</h1>
  <span class="state" id="stateLabel">booting</span>
  <div class="spacer"></div>
  <div class="tabs">
    <button class="tab active" data-pane="dash">Progress</button>
    <button class="tab" data-pane="log">Build output</button>
  </div>
  <button id="rebuildBtn">Rebuild</button>
</header>
<div class="conflict-panel" id="conflictPanel">
  <h2>Pending changes conflict with an external rulebook edit</h2>
  <p>
    There are live edits not yet saved into <code>effortless-rulebook.json</code>, and the
    rulebook file on disk just changed independently (hand-edited, or written by another
    process) before those edits were saved. Pick how to proceed -- the build is paused until
    you choose:
  </p>
  <div class="conflict-choices">
    <button class="recommended" data-choice="save-as-unresolved">
      Save as unresolved merge file (safe default)
    </button>
    <button data-choice="discard">
      Discard my pending changes
    </button>
    <button class="danger" data-choice="overwrite">
      Overwrite the external edit (not recommended)
    </button>
  </div>
</div>
<div class="fail-panel" id="failPanel">
  <h2 id="failTitle">Some build steps failed</h2>
  <p id="failIntro"></p>
  <p class="fail-links">
    Which step, and why: see the marked step(s) below
    &nbsp;&middot;&nbsp; Raw detail (stack traces, inner exceptions): <a href="/__boot/errors">/__boot/errors</a>
    &nbsp;&middot;&nbsp; What is running right now: <a href="/__boot/status">/__boot/status</a>
  </p>
</div>
<main id="main">
  <section id="dashPane">
    <p class="lead">
      This container turns your <code>effortless-rulebook.json</code> into three running things:
      a <b>database</b> holding your data, an <b>API</b> that serves it, and the <b>admin portal</b>
      you land in when this finishes. Each step below is one generator, and the whole sequence runs
      again every time you rebuild. Nothing here is hidden -- the unedited build output is under the
      <b>Build output</b> tab.
    </p>
    <h2 class="sec">What is running right now</h2>
    <div class="tiles" id="tiles"></div>
    <h2 class="sec">Build steps</h2>
    <div class="progress"><div class="progress-bar" id="progressBar"></div></div>
    <div class="progress-label" id="progressLabel">Waiting for the build to start...</div>
    <div class="rail" id="rail"></div>
  </section>
  <section id="logPane"><div id="log"></div></section>
</main>
<div class="hint" id="hint">Waiting for the container to finish its first build. This page auto-refreshes into the app once it's ready.</div>
<script>
  const logEl = document.getElementById('log');
  const dot = document.getElementById('dot');
  const stateLabel = document.getElementById('stateLabel');
  const hint = document.getElementById('hint');
  const rebuildBtn = document.getElementById('rebuildBtn');
  const conflictPanel = document.getElementById('conflictPanel');
  const failPanel = document.getElementById('failPanel');
  const failTitle = document.getElementById('failTitle');
  const failIntro = document.getElementById('failIntro');
  const mainEl = document.getElementById('main');
  const tilesEl = document.getElementById('tiles');
  const railEl = document.getElementById('rail');
  const progressBar = document.getElementById('progressBar');
  const progressLabel = document.getElementById('progressLabel');

  // This page is reachable two ways: as the placeholder the proxy serves while
  // the app is not up, and EXPLICITLY at /__boot/ while it is. The auto-reload
  // below must not fire in the second case -- reloading /__boot/ just serves
  // /__boot/ again, which would spin forever instead of showing diagnostics.
  const ON_BOOT_PATH = location.pathname.replace(/[/]+$/, '') === '/__boot';
  // Rebuild flows that intentionally send the user here include the app route
  // they came from. Keep plain /__boot/ stable for diagnostics, but return from
  // /__boot/?return=... after the build reaches a serving state. Accept local
  // absolute paths only: this must never become an open redirect.
  const requestedReturnPath = new URLSearchParams(location.search).get('return');
  const AUTO_RETURN_PATH = requestedReturnPath
    && requestedReturnPath.indexOf('/') === 0
    && requestedReturnPath.indexOf('//') !== 0
    && requestedReturnPath.indexOf('/__boot') !== 0
      ? requestedReturnPath
      : null;

  function switchTab(pane) {
    document.querySelectorAll('.tab').forEach((t) => {
      t.classList.toggle('active', t.dataset.pane === pane);
    });
    mainEl.className = pane === 'log' ? 'raw' : '';
    if (pane === 'log') mainEl.scrollTop = mainEl.scrollHeight;
  }

  function appendLine(line) {
    logEl.textContent += line + "\\n";
    // Only chase the tail while the raw pane is the one actually on screen --
    // otherwise every incoming line yanks the dashboard back to the bottom.
    if (mainEl.className === 'raw') mainEl.scrollTop = mainEl.scrollHeight;
    handleLogLine(line);
  }

  // ---------------------------------------------------------------------
  // The dashboard.
  //
  // Three sources, deliberately layered so the page is useful at every moment
  // rather than only after a build finishes:
  //   1. GET /__boot/pipeline  -- the WHOLE step list, up front, before anything
  //      has run. This is what makes "how many steps, and what are they for?"
  //      answerable at t=0.
  //   2. the live log stream    -- which step is running right now, parsed off the
  //      CLI banner it prints as it starts each one.
  //   3. GET /__boot/errors     -- authoritative per-step status once the build
  //      ends, which CORRECTS anything (2) guessed.
  // Nothing here gates the app: every fetch below is fire-and-forget with a
  // swallowed rejection, and a failure just leaves the rail as it was.
  // ---------------------------------------------------------------------

  // The plain-language title/why for each step arrives ON the pipeline payload
  // (see STEP_COPY server-side) -- the admin portal's build monitor renders the
  // same rail from the same route, and one copy of the words is what keeps the
  // two from drifting apart.
  const COMPONENT_COPY = {
    postgres: ['Database', 'Holds your rulebook data. The launcher prints the host port for direct connections.'],
    api: ['API', 'Serves that data over HTTP. The launcher prints its host URL for direct debugging.'],
    portal: ['Admin portal', 'The browsable site over your rulebook. It replaces this boot page at the current URL once ready.'],
    bootServer: ['This page', 'Owns the published UI port for the whole life of the container, so you always get an answer here -- even when everything else is down.'],
  };
  // Literal characters, not \\uXXXX escapes: this page is a template literal, so a
  // "\\u2713" written here survives as the six characters backslash-u-2-7-1-3
  // rather than becoming a check mark. Same trap as everything else in this file.
  // A pending step shows its own number instead of a symbol (see renderRail).
  const ICONS = {
    running: '▶',
    succeeded: '✓',
    failed: '✕',
    skipped: '–',
  };
  const CHIP = {
    running: ['now', 'running now'],
    skipped: ['off', 'turned off'],
    failed: ['bad', 'failed'],
  };

  let pipeline = [];      // [{name, relativePath, commandLine, description, isDisabled}]
  let stepState = {};     // name -> pending | running | succeeded | failed | skipped
  let stepDetail = {};    // name -> the errors.json record (or a scraped log line)
  let runningStep = null;
  let sawErrorInStep = false;

  // The CLI announces each step as "  **** /postgres: rulebooktopostgres ****".
  // Parsed with string ops rather than a regex ON PURPOSE: this whole page lives
  // inside a template literal, which eats single backslashes, so a regex like
  // \\s or \\* is one missed escape away from a SyntaxError that kills the entire
  // script (see the ESCAPING TRAP note above -- that has already happened once).
  function parseBanner(line) {
    const t = String(line).trim();
    if (t.length < 10 || t.indexOf('****') !== 0) return null;
    if (t.lastIndexOf('****') !== t.length - 4) return null;
    const inner = t.slice(4, t.length - 4).trim();
    const sep = inner.lastIndexOf(': ');
    if (sep < 0) return null;
    const name = inner.slice(sep + 2).trim();
    if (!name || name.indexOf(' ') >= 0) return null;
    return { relativePath: inner.slice(0, sep).trim(), name: name };
  }

  const SKIP_MARKER = 'SKIPPING DISABLED TRANSPILER: ';

  function titleFor(step) { return step.title || step.name; }

  function whyFor(step) {
    if (step.why) return step.why;
    if (step.description) return step.description;
    return 'Runs: effortless ' + (step.commandLine || step.name);
  }

  function finishRunningStep() {
    if (!runningStep) return;
    // Optimistic, and corrected by errors.json the moment the build ends -- but
    // right while a build is in flight it is the only signal there is, and a rail
    // that only goes green after the whole build finishes tells you nothing while
    // you are waiting.
    stepState[runningStep] = sawErrorInStep ? 'failed' : 'succeeded';
    runningStep = null;
    sawErrorInStep = false;
  }

  function resetSteps() {
    stepState = {};
    stepDetail = {};
    runningStep = null;
    sawErrorInStep = false;
    pipeline.forEach((s) => { stepState[s.name] = s.isDisabled ? 'skipped' : 'pending'; });
    renderRail();
  }

  function handleLogLine(line) {
    const banner = parseBanner(line);
    if (banner) {
      finishRunningStep();
      runningStep = banner.name;
      sawErrorInStep = false;
      stepState[runningStep] = 'running';
      renderRail();
      return;
    }
    const si = line.indexOf(SKIP_MARKER);
    if (si >= 0) {
      finishRunningStep();
      const skipped = line.slice(si + SKIP_MARKER.length).trim();
      if (skipped) stepState[skipped] = 'skipped';
      renderRail();
      return;
    }
    if (runningStep && (line.indexOf('ERROR:') === 0 || line.indexOf('TRANSPILER ERROR') >= 0)) {
      sawErrorInStep = true;
      if (!stepDetail[runningStep]) stepDetail[runningStep] = { message: line.trim() };
    }
    if (line.indexOf('effortless build finished') >= 0) {
      finishRunningStep();
      renderRail();
      // errors.json is written as the CLI exits, so give it a beat before asking.
      setTimeout(refreshFailures, 500);
    }
  }

  // errors.json's steps[] is the authoritative record of what the build actually
  // did, in order -- it overrides everything the log-scraping above guessed.
  function applyReport(report) {
    (report.steps || []).forEach((s) => {
      if (s && s.name && s.status) stepState[s.name] = s.status;
    });
    (report.errors || []).forEach((e) => {
      if (!e || !e.name) return;
      stepState[e.name] = 'failed';
      stepDetail[e.name] = e;
    });
    renderRail();
  }

  // A clean build (no errors.json at all) means every enabled step ran and
  // succeeded -- that is the contract errors.json carries by its ABSENCE. Without
  // this, a page opened after a fast build shows a rail stuck on 'pending',
  // because the log tail no longer contains the banners.
  // Everything EXCEPT a skipped step, deliberately -- including one showing as
  // failed. A red row left over from the previous build would otherwise survive a
  // rebuild that fixed it, which is the same stale-report problem the CLI solves
  // by deleting errors.json on a clean build.
  function markAllSucceeded() {
    Object.keys(stepState).forEach((n) => {
      if (stepState[n] !== 'skipped') stepState[n] = 'succeeded';
    });
    stepDetail = {};
    runningStep = null;
    renderRail();
  }

  function renderRail() {
    const list = pipeline.length
      ? pipeline
      : Object.keys(stepState).map((n) => ({ name: n }));
    railEl.innerHTML = '';

    if (!list.length) {
      const p = document.createElement('div');
      p.className = 'why';
      p.textContent = 'Reading the build pipeline...';
      railEl.appendChild(p);
      progressLabel.textContent = 'Waiting for the build to start...';
      return;
    }

    let total = 0, done = 0, failed = 0, current = '';
    list.forEach((step, i) => {
      const st = stepState[step.name] || 'pending';
      if (st !== 'skipped') {
        total++;
        if (st === 'succeeded' || st === 'failed') done++;
        if (st === 'failed') failed++;
        if (st === 'running') current = titleFor(step);
      }

      const row = document.createElement('div');
      row.className = 'step ' + st;

      // The gutter is a fixed-width lane so the pipe stays straight, but the
      // glyph inside it grows from a 34px disc to a 62px arrow when the step is
      // the one running -- the size change itself is the "you are here".
      const gutter = document.createElement('div');
      gutter.className = 'gutter';
      const glyph = document.createElement('span');
      glyph.className = 'glyph';
      glyph.textContent = ICONS[st] || String(i + 1);
      gutter.appendChild(glyph);
      row.appendChild(gutter);

      const body = document.createElement('div');
      body.className = 'body';

      const name = document.createElement('div');
      name.className = 'name';
      const nameText = document.createElement('span');
      nameText.textContent = titleFor(step);
      name.appendChild(nameText);
      if (CHIP[st]) {
        const chip = document.createElement('span');
        chip.className = 'chip ' + CHIP[st][0];
        chip.textContent = CHIP[st][1];
        name.appendChild(chip);
      }
      body.appendChild(name);

      const why = document.createElement('div');
      why.className = 'why';
      why.textContent = whyFor(step);
      body.appendChild(why);

      // Failure detail INLINE, on the step that failed. The whole point is that
      // nobody should have to go hunting for one ERROR: line in the raw log.
      if (st === 'failed') {
        const d = stepDetail[step.name] || {};
        const err = document.createElement('div');
        err.className = 'err';
        err.textContent = d.message || 'This step failed but reported no message.';
        body.appendChild(err);

        const trace = (d.transpilerException || d.cliException || null);
        if (trace) {
          const det = document.createElement('details');
          const sum = document.createElement('summary');
          sum.textContent = 'Stack trace / inner exceptions';
          const pre = document.createElement('pre');
          pre.textContent = describeException(trace);
          det.appendChild(sum);
          det.appendChild(pre);
          body.appendChild(det);
        }

        const toLog = document.createElement('button');
        toLog.className = 'linkish';
        toLog.textContent = 'Show the raw build output';
        toLog.onclick = () => switchTab('log');
        body.appendChild(toLog);
      }

      const det = document.createElement('details');
      const sum = document.createElement('summary');
      sum.textContent = 'Technical detail';
      const pre = document.createElement('pre');
      pre.textContent =
        'step:      ' + step.name + '\\n' +
        'runs in:   ' + (step.relativePath || '(project root)') + '\\n' +
        'command:   effortless ' + (step.commandLine || '(unknown)') +
        (step.description ? '\\n\\n' + step.description : '');
      det.appendChild(sum);
      det.appendChild(pre);
      body.appendChild(det);

      row.appendChild(body);
      railEl.appendChild(row);
    });

    // Half-credit for the step in flight, so the bar advances TWICE per step
    // rather than sitting perfectly still for however long a generator takes.
    const eff = done + (current ? 0.5 : 0);
    const pct = total ? Math.round((eff / total) * 100) : 0;
    progressBar.style.width = pct + '%';
    progressBar.className = 'progress-bar' + (failed ? ' failed' : '') + (current ? ' active' : '');

    progressLabel.innerHTML = '';
    if (current) {
      const lead = document.createElement('span');
      lead.textContent = 'Step ' + (done + 1) + ' of ' + total + ' -- ';
      const strong = document.createElement('b');
      strong.textContent = current;
      progressLabel.appendChild(lead);
      progressLabel.appendChild(strong);
    } else {
      progressLabel.textContent = done >= total && total
        ? (failed
            ? done + ' of ' + total + ' steps finished, ' + failed + ' of them failed.'
            : 'All ' + total + ' steps finished.')
        : done + ' of ' + total + ' steps finished.';
    }
  }

  function describeException(ex) {
    let out = '';
    let cur = ex;
    let depth = 0;
    while (cur && depth < 8) {
      out += (depth ? '\\ncaused by: ' : '') + (cur.type || '(unknown type)') + ': ' + (cur.message || '');
      if (cur.stackTrace) out += '\\n' + cur.stackTrace;
      cur = cur.inner;
      depth++;
    }
    return out;
  }

  function renderTiles(status) {
    const comps = (status && status.components) || {};
    tilesEl.innerHTML = '';
    ['postgres', 'api', 'portal', 'bootServer'].forEach((key) => {
      const copy = COMPONENT_COPY[key] || [key, ''];
      const c = comps[key];
      // We are talking to the boot server right now, so it is up by definition --
      // never report it as unknown just because the snapshot file is not written yet.
      const st = key === 'bootServer' ? 'up' : (c && c.status ? c.status : 'unknown');

      const tile = document.createElement('div');
      tile.className = 'tile';
      const h = document.createElement('h3');
      h.textContent = copy[0];
      const pill = document.createElement('span');
      pill.className = 'pill ' + (st === 'up' ? 'up' : st === 'down' ? 'down' : 'unknown');
      pill.textContent = st === 'up' ? 'up' : st === 'down' ? 'down' : 'starting';
      h.appendChild(pill);
      const p = document.createElement('p');
      p.textContent = copy[1];
      tile.appendChild(h);
      tile.appendChild(p);
      // Which build of the generator tool produced what's currently running --
      // absent for bootServer (not generated by a versioned tool) and for a
      // status snapshot written before LastVersionUsed was tracked.
      if (c && c.version) {
        const v = document.createElement('p');
        v.className = 'tile-version';
        v.textContent = 'built by ' + c.version;
        tile.appendChild(v);
      }
      tilesEl.appendChild(tile);
    });
  }

  function refreshPipeline() {
    return fetch('/__boot/pipeline').then(r => r.json()).then((payload) => {
      const steps = (payload && payload.steps) || [];
      if (!steps.length) return;
      pipeline = steps;
      // Seed any step we have not heard about yet, without clobbering statuses
      // already derived from the log or from errors.json.
      pipeline.forEach((s) => {
        if (!(s.name in stepState)) stepState[s.name] = s.isDisabled ? 'skipped' : 'pending';
      });
      renderRail();
    }).catch(() => {});
  }

  function refreshStatus() {
    return fetch('/__boot/status').then(r => r.json()).then(renderTiles).catch(() => {});
  }

  // Pull the structured failure record rather than asking the user to spot an
  // ERROR line in a few hundred lines of npm/SQL output. A silent failure is the
  // specific thing this page exists to prevent.
  function refreshFailures() {
    fetch('/__boot/errors').then(r => r.json()).then((payload) => {
      if (!payload || !payload.hasErrors || !payload.report) {
        failPanel.classList.remove('show');
        return;
      }
      const report = payload.report;
      const errs = report.errors || [];
      failTitle.textContent = errs.length === 1
        ? '1 build step failed'
        : errs.length + ' build steps failed';
      failIntro.textContent =
        'The build was NOT aborted -- ' + (report.succeededSteps || 0) + ' of ' +
        (report.totalSteps || 0) + ' step(s) succeeded and whatever they generated is running. ' +
        'Only the output of the failed step(s) is missing.';
      failPanel.classList.add('show');
      applyReport(report);
    }).catch(() => {});
  }

  let lastSeenState = '';
  let sawBuildForReturn = false;
  let returnTimer = null;

  function setState(state) {
    stateLabel.textContent = state;
    dot.className = 'dot' + (state === 'ready' ? ' ready'
      : state === 'degraded' ? ' degraded'
      : state === 'error' ? ' error'
      : state === 'awaiting-conflict-resolution' ? ' conflict' : '');
    conflictPanel.classList.toggle('show', state === 'awaiting-conflict-resolution');

    // A NEW build is starting: clear the rail so the previous run's greens and
    // reds are not shown as if they described this one. Only on the transition,
    // not on every repeat of the same state.
    if (state === 'building' && lastSeenState !== 'building') {
      sawBuildForReturn = true;
      if (returnTimer) {
        clearTimeout(returnTimer);
        returnTimer = null;
      }
      failPanel.classList.remove('show');
      refreshPipeline();
      resetSteps();
    }
    lastSeenState = state;

    refreshStatus();

    if (state === 'degraded' || state === 'error') refreshFailures();
    // Clean build: errors.json is absent BY CONTRACT, so there is no per-step
    // record to read -- the absence itself is the all-succeeded signal.
    if (state === 'ready') { failPanel.classList.remove('show'); markAllSucceeded(); }

    // NOTE: there is deliberately no 'rebuild-prompted' state. Asking whether
    // to rebuild must not kick the user out of the app into this page, so the
    // entrypoint leaves the state at 'ready' and the question is asked as a
    // toast inside the app instead (see /__boot/rebuild-prompt and the
    // portal's components/RebuildPrompt.jsx).
    //
    // 'degraded' means the app IS up and serving, it just built with one or
    // more failed steps -- so it hands off to the app exactly like 'ready'.
    // Reporting it as a distinct state (rather than folding it into 'ready')
    // is what keeps a partial failure visible instead of silent.
    if (state === 'ready' || state === 'degraded') {
      hint.textContent = state === 'degraded'
        ? 'Build finished with failures -- loading the app anyway; the tab for the failed step will be empty.'
        : 'Build finished -- loading the app...';
      if (AUTO_RETURN_PATH && sawBuildForReturn) {
        if (returnTimer) clearTimeout(returnTimer);
        returnTimer = setTimeout(() => window.location.replace(AUTO_RETURN_PATH), 600);
      } else if (AUTO_RETURN_PATH) {
        hint.textContent = 'Waiting for the requested rebuild to start...';
      } else if (!ON_BOOT_PATH) {
        setTimeout(() => window.location.reload(), 600);
      }
    } else if (state === 'error') {
      hint.textContent = 'The app could not start -- see the failures above and the log below. Fix the rulebook and save, or click Rebuild.';
    } else if (state === 'awaiting-conflict-resolution') {
      hint.textContent = 'Build paused -- choose a resolution above before it continues.';
    } else if (state === 'building') {
      hint.textContent = 'Building...';
    } else {
      hint.textContent = 'Waiting for the container to finish its build. This page auto-refreshes into the app once ready.';
    }
  }

  document.querySelectorAll('.tab').forEach((t) => {
    t.onclick = () => switchTab(t.dataset.pane);
  });

  // Render something the instant the page opens, before any fetch lands.
  renderTiles(null);
  renderRail();

  // Order matters: the pipeline first, so replaying the log tail below has a rail
  // to mark up rather than inventing steps out of banner lines alone.
  refreshPipeline()
    .then(() => fetch('/__boot/log').then(r => r.json()))
    .then(({ lines, state }) => {
      lines.forEach(appendLine);
      setState(state);
      // A page opened AFTER a build finished has no 'building' transition to react
      // to, so reconcile once on load: errors.json if the last build failed,
      // all-succeeded if it was clean and the app is serving.
      if (state === 'degraded' || state === 'error') refreshFailures();
      else if (state === 'ready') markAllSucceeded();
    })
    .catch(() => {});

  const es = new EventSource('/__boot/events');
  es.onmessage = (e) => appendLine(JSON.parse(e.data).line);
  es.addEventListener('state', (e) => setState(JSON.parse(e.data).state));

  // The component tiles are the answer to "which parts of this thing are alive?",
  // which changes independently of the log (a service can die long after the build
  // ended), so they poll rather than waiting for a state change to push them.
  setInterval(refreshStatus, 2500);
  refreshStatus();

  rebuildBtn.onclick = () => {
    rebuildBtn.disabled = true;
    fetch('/__boot/rebuild', { method: 'POST' }).finally(() => {
      setTimeout(() => { rebuildBtn.disabled = false; }, 3000);
    });
  };

  conflictPanel.querySelectorAll('button[data-choice]').forEach((btn) => {
    btn.onclick = () => {
      conflictPanel.querySelectorAll('button').forEach((b) => { b.disabled = true; });
      fetch('/__boot/resolve-conflict', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ choice: btn.dataset.choice }),
      }).catch(() => {}).finally(() => {
        conflictPanel.querySelectorAll('button').forEach((b) => { b.disabled = false; });
      });
    };
  });
</script>
</body>
</html>
`;

function proxyToInternalUI(req, res) {
  const proxyReq = http.request(
    {
      host: '127.0.0.1',
      port: INTERNAL_UI_PORT,
      path: req.url,
      method: req.method,
      headers: req.headers,
    },
    (proxyRes) => {
      res.writeHead(proxyRes.statusCode, proxyRes.headers);
      proxyRes.pipe(res);
    },
  );
  // THE WHITE-SCREEN FIX. The state file can say the app is serving while the
  // Vite dev server behind it is not actually answering -- it died after a
  // successful start, or is mid-restart during a rebuild. The old behavior
  // returned a bare 502 text body for EVERY request, which for a document
  // request is at least readable, but for the app's JS/CSS assets means the
  // browser gets 502s for its module graph and paints nothing at all: a blank
  // page with the real problem visible only in devtools. Serving the boot page
  // (with its live log tail, /__boot/errors link, and Rebuild button) for
  // document requests instead means a proxy failure ALWAYS produces something
  // that explains itself. Sub-resource requests still get a plain error, since
  // returning HTML for a .js request would only produce a different confusion.
  proxyReq.on('error', (err) => {
    if (res.headersSent) { try { res.end(); } catch {} return; }
    const accept = String(req.headers['accept'] || '');
    const wantsHtml = req.method === 'GET' && accept.includes('text/html');
    if (wantsHtml) {
      res.writeHead(503, { 'content-type': 'text/html', 'cache-control': 'no-store' });
      res.end(BOOT_PAGE);
    } else {
      res.writeHead(502, { 'content-type': 'text/plain' });
      res.end(`rulebook-editor: internal UI on :${INTERNAL_UI_PORT} is not answering (${err && err.code ? err.code : 'proxy error'}). See /__boot/ for the build log and /__boot/status for what is running.`);
    }
  });
  req.pipe(proxyReq);
}

// Static output from the two "document" transpilers (RuleSpeak® -- all 10
// languages in one multilingual document, XLSX export) -- these are plain
// files dropped by `effortless build` into fixed container directories (see
// effortless.editor.json's RelativePath for each), not apps with their own
// server. Whitelisted prefix -> directory map only (no arbitrary path
// passthrough), and each request is re-resolved against the real directory
// + guarded against `..` escape before any read.
const STATIC_TOOL_DIRS = {
  '/__tools/rulespeak': '/app/effortless-root/rulespeak',
  '/__tools/xlsx': '/app/effortless-root/xlsx',
  '/__tools/progress-report': '/app/effortless-root/progress-report',
};
const path = require('path');

function serveStaticTool(req, res, urlPrefix, rootDir) {
  // req.url still carries the query string (e.g. "?lang=zh" from the
  // RuleSpeak® language picker) -- strip it before treating the remainder as
  // a filesystem path, or a request for rulespeak.html?lang=zh resolves to
  // a literal (nonexistent) file named "rulespeak.html?lang=zh".
  const urlPath = req.url.split('?')[0];
  const rel = decodeURIComponent(urlPath.slice(urlPrefix.length));

  // A bare directory request (no filename) resolves to whatever single file
  // is actually in that directory, rather than a hardcoded name -- e.g.
  // rulebook-to-xlsx names its output after the (slugified) rulebook, not a
  // fixed "rulebook.xlsx", so the portal can link to "/__tools/xlsx/"
  // without needing to know that slug.
  if (!rel || rel === '/') {
    let entries;
    try {
      entries = fs.readdirSync(rootDir).filter((f) => !f.startsWith('.'));
    } catch {
      entries = [];
    }
    if (entries.length === 1) {
      serveFile(res, path.join(rootDir, entries[0]), entries[0]);
      return;
    }
    if (entries.includes('index.html')) {
      serveFile(res, path.join(rootDir, 'index.html'), 'index.html');
      return;
    }
    res.writeHead(404, { 'content-type': 'text/plain' });
    res.end(`no single file to serve in ${rootDir} (found: ${entries.join(', ') || 'nothing -- has the build run yet? see /__boot/log'})`);
    return;
  }

  const target = path.normalize(path.join(rootDir, rel));
  if (!target.startsWith(path.normalize(rootDir))) {
    res.writeHead(400, { 'content-type': 'text/plain' });
    res.end('bad path');
    return;
  }
  serveFile(res, target, rel);
}

function serveFile(res, target, rel) {
  fs.readFile(target, (err, data) => {
    if (err) {
      res.writeHead(404, { 'content-type': 'text/plain' });
      res.end(`not found: ${rel} (has the build run yet? see /__boot/log)`);
      return;
    }
    const ext = path.extname(target).toLowerCase();
    const contentType =
      ext === '.html' ? 'text/html' :
      ext === '.md' ? 'text/markdown' :
      ext === '.xlsx' ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' :
      ext === '.json' ? 'application/json' :
      'application/octet-stream';
    res.writeHead(200, { 'content-type': contentType });
    res.end(data);
  });
}

const server = http.createServer((req, res) => {
  try {
    // Route on pathname, not the raw URL. Rebuild progress URLs carry
    // ?return=<app-route>; comparing req.url literally made that request miss
    // /__boot/ and get proxied to Vite, so the boot page's return logic never
    // ran.
    const requestPath = new URL(req.url, 'http://boot.local').pathname;
    for (const [prefix, dir] of Object.entries(STATIC_TOOL_DIRS)) {
      if (requestPath === prefix || requestPath.startsWith(prefix + '/')) {
        serveStaticTool(req, res, prefix, dir);
        return;
      }
    }

    if (requestPath === '/__boot/log') {
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ lines: tailLines(400), state: readState() }));
      return;
    }
    // The structured record of what failed in the last build (the CLI's
    // errors.json, verbatim). ABSENT means the last build was clean -- that is
    // the contract, so a 200 with hasErrors:false is the honest answer here
    // rather than a 404 the caller has to interpret.
    if (requestPath === '/__boot/errors') {
      const errors = readJsonFile(ERRORS_FILE);
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify(errors
        ? { hasErrors: true, report: errors }
        : { hasErrors: false, report: null, note: 'the last build reported no failed steps' }));
      return;
    }
    // What is actually alive right now. Written by container-entrypoint.sh after
    // every build; if it is missing we still answer, because a caller asking
    // "what is up?" during boot deserves an answer, not a 404.
    if (requestPath === '/__boot/status') {
      const status = readJsonFile(STATUS_FILE) || {
        state: readState(),
        note: 'no status snapshot written yet -- the first build has not finished',
      };
      status.state = readState();
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify(status));
      return;
    }
    // The declared build pipeline, in order. Answered even when the file is not
    // readable yet (first seconds of boot) -- an empty list with a note beats a
    // 404 the page has to special-case.
    if (requestPath === '/__boot/pipeline') {
      const steps = readPipeline();
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify(steps.length
        ? { steps }
        : { steps: [], note: 'effortless.json is not readable yet -- it is seeded early in boot, before the first build' }));
      return;
    }
    // The boot/diagnostics page ON DEMAND, even while the app is up and being
    // proxied. Without this there is no way back to the log/errors view once the
    // portal takes over the port -- which is exactly when you most want it, since
    // a degraded build means some tab in that portal is missing its data.
    if (requestPath === '/__boot' || requestPath === '/__boot/') {
      res.writeHead(200, { 'content-type': 'text/html' });
      res.end(BOOT_PAGE);
      return;
    }
    if (requestPath === '/__boot/events') {
      res.writeHead(200, {
        'content-type': 'text/event-stream',
        'cache-control': 'no-cache',
        connection: 'keep-alive',
      });
      res.write(': connected\n\n');
      sseClients.add(res);
      req.on('close', () => sseClients.delete(res));
      return;
    }
    if (requestPath === '/__boot/rebuild' && req.method === 'POST') {
      fs.writeFileSync(REBUILD_TRIGGER, String(Date.now()));
      res.writeHead(202, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ triggered: true }));
      return;
    }
    if (requestPath === '/__boot/resolve-conflict' && req.method === 'POST') {
      let body = '';
      req.on('data', (chunk) => { body += chunk; });
      req.on('end', () => {
        let choice = '';
        try {
          choice = (JSON.parse(body || '{}').choice || '').toString();
        } catch {
          choice = '';
        }
        const VALID_CHOICES = new Set(['save-as-unresolved', 'discard', 'overwrite']);
        if (!VALID_CHOICES.has(choice)) {
          res.writeHead(400, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: `invalid choice: ${choice || '(empty)'}` }));
          return;
        }
        // container-entrypoint.sh's check_uncommitted_before_build() is
        // blocked in a poll-until-file-exists loop on this exact path --
        // writing it here is the entire hand-off. It reads the choice,
        // deletes this file, and proceeds.
        fs.writeFileSync(CONFLICT_CHOICE_FILE, choice);
        res.writeHead(202, { 'content-type': 'application/json' });
        res.end(JSON.stringify({ accepted: choice }));
      });
      return;
    }
    // Enable/disable pipeline steps by name, then (optionally) kick a rebuild.
    // This is the ONLY write path into effortless.json's IsDisabled flags, and it
    // exists so the portal's language picker can turn RuleSpeak® languages on and
    // off without anyone hand-editing the file: which languages the portal offers
    // is DERIVED from which of the two rulespeak steps are enabled, so the toggle
    // and the dropdown are the same fact viewed from two places.
    //
    // Body: { steps: { <stepName>: <bool isDisabled>, ... }, rebuild?: bool }
    // Only IsDisabled is ever touched -- names that are not already in the file are
    // ignored rather than created, so a stale/typo'd portal build cannot invent
    // pipeline steps that would then fail to run.
    if (requestPath === '/__boot/pipeline-toggle' && req.method === 'POST') {
      let body = '';
      req.on('data', (chunk) => { body += chunk; });
      req.on('end', () => {
        let payload;
        try {
          payload = JSON.parse(body || '{}');
        } catch {
          res.writeHead(400, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: 'body is not valid JSON' }));
          return;
        }
        const steps = (payload && payload.steps) || {};
        const names = Object.keys(steps);
        if (!names.length) {
          res.writeHead(400, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: 'no steps given -- expected { steps: { name: isDisabled } }' }));
          return;
        }
        const cfg = readJsonFile(PIPELINE_FILE);
        if (!cfg || !Array.isArray(cfg.ProjectTranspilers)) {
          res.writeHead(503, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: `${PIPELINE_FILE} is not readable/parseable yet` }));
          return;
        }
        const applied = [];
        const unknown = [];
        for (const name of names) {
          const step = cfg.ProjectTranspilers.find((t) => t.Name === name);
          if (!step) { unknown.push(name); continue; }
          step.IsDisabled = !!steps[name];
          applied.push({ name, isDisabled: step.IsDisabled });
        }
        if (!applied.length) {
          res.writeHead(404, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: 'none of the named steps exist in the pipeline', unknown }));
          return;
        }
        // Write through a temp file in the same directory + rename, so a reader
        // (this server's own GET /__boot/pipeline, or the CLI mid-build) can never
        // observe a half-written effortless.json.
        try {
          const tmp = PIPELINE_FILE + '.tmp-toggle';
          fs.writeFileSync(tmp, JSON.stringify(cfg, null, 2) + '\n');
          fs.renameSync(tmp, PIPELINE_FILE);
        } catch (err) {
          res.writeHead(500, { 'content-type': 'application/json' });
          res.end(JSON.stringify({ error: `could not write ${PIPELINE_FILE}: ${err && err.message}` }));
          return;
        }
        // Same trigger the Rebuild button uses -- the entrypoint is polling it.
        let rebuilding = false;
        if (payload.rebuild) {
          try {
            fs.writeFileSync(REBUILD_TRIGGER, String(Date.now()));
            rebuilding = true;
          } catch { rebuilding = false; }
        }
        res.writeHead(202, { 'content-type': 'application/json' });
        res.end(JSON.stringify({ applied, unknown, rebuilding }));
      });
      return;
    }
    // Is a rebuild currently being offered, and for how much longer? Polled by
    // the app's RebuildPrompt toast (rulebook-to-vite-admin-portal).
    if (requestPath === '/__boot/rebuild-prompt') {
      res.writeHead(200, { 'content-type': 'application/json' });
      res.end(JSON.stringify(readRebuildPrompt()));
      return;
    }
    // Yes / no to that offer. container-entrypoint.sh's prompt_for_rebuild()
    // is polling for whichever of these two files appears first.
    if (requestPath === '/__boot/rebuild-confirm' && req.method === 'POST') {
      fs.writeFileSync(REBUILD_PROMPT_CONFIRM_FILE, String(Date.now()));
      res.writeHead(202, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ confirmed: true }));
      return;
    }
    if (requestPath === '/__boot/rebuild-dismiss' && req.method === 'POST') {
      fs.writeFileSync(REBUILD_PROMPT_DISMISS_FILE, String(Date.now()));
      res.writeHead(202, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ dismissed: true }));
      return;
    }

    const state = readState();
    if (isAppServing(state)) {
      proxyToInternalUI(req, res);
      return;
    }

    res.writeHead(200, { 'content-type': 'text/html' });
    res.end(BOOT_PAGE);
  } catch (err) {
    console.error('[boot-server] request handler error:', req.url, err);
    if (!res.headersSent) {
      res.writeHead(500, { 'content-type': 'text/plain' });
      res.end(`boot-server internal error: ${err && err.message ? err.message : err}`);
    } else {
      res.end();
    }
  }
});

// A single malformed/unexpected request must never take the whole container's
// proxy down -- log and keep serving instead of letting Node's default
// uncaughtException/unhandledRejection behavior exit the process.
process.on('uncaughtException', (err) => {
  console.error('[boot-server] uncaught exception (process kept alive):', err);
});
process.on('unhandledRejection', (err) => {
  console.error('[boot-server] unhandled rejection (process kept alive):', err);
});

server.listen(EXTERNAL_PORT, '0.0.0.0', () => {
  console.log(`[boot-server] listening on :${EXTERNAL_PORT} (proxies to internal UI on :${INTERNAL_UI_PORT} once ready)`);
});
