#!/bin/bash
# container-entrypoint.sh -- GENERATED by effortless-rulebook-editor.
#
# Boot sequence inside the container:
#   0. start boot-server.js on the EXTERNAL UI port (5174) IMMEDIATELY -- this
#      is the very first thing that happens, before Postgres or any build, so
#      a browser tab opened at container-start shows a live progress page
#      instead of a connection-refused error. It streams the build log over
#      SSE and exposes a Rebuild button; see boot-server.js for the full
#      contract (state file + log file it watches).
#   1. start local Postgres cluster (bundled in-image, single-container app)
#   2. run `effortless build` once (generates SQL + runs the database reset
#      wrapper against
#      the local Postgres + generates the Node API + Vite UI + RuleSpeak® +
#      RuleSpeak-DE + XLSX export) -- consumed transpilers resolve from the
#      normal published registry, same as any other effortless transpiler
#   3. start the generated Node API and Vite UI (Vite binds the INTERNAL port
#      5175 -- boot-server.js proxies 5174 -> 5175 once the build succeeds)
#   4. watch the mounted effortless-rulebook.json AND the boot server's
#      rebuild-trigger file for changes. The two are NOT treated the same:
#        - rebuild-trigger (the Rebuild button, or POST /__boot/rebuild) is an
#          explicit request, so it rebuilds immediately; whereas
#        - a change to the rulebook FILE only OFFERS a rebuild (see
#          prompt_for_rebuild below). A rebuild drops and recreates the whole
#          database, so it is never started on the user's behalf just because
#          a file changed -- the offer appears as a toast in the running app
#          and expires on its own if nobody answers.
#      Once a rebuild is actually going ahead, check for pending uncommitted
#      changes (see check_uncommitted_before_build below -- the very first
#      build in step 2 is never gated, since nothing can be pending yet), then
#      kill+rebuild+restart everything. Loop forever.

set -uo pipefail

BOOT_STATE_FILE="/tmp/boot-state"
BUILD_LOG_FILE="/tmp/current-build.log"
REBUILD_TRIGGER_FILE="/tmp/rebuild-trigger"
# Both touched immediately so the RULEBOOK_FILENAME check just below can write
# to them under `set -u` (the fuller boot-state init these are also part of
# happens again, harmlessly, a few lines down alongside the other boot files).
echo "booting" > "$BOOT_STATE_FILE"
touch "$BUILD_LOG_FILE"

# RULEBOOK_FILENAME is set by edit-rulebook.sh's `docker run -e` from its own
# -p rulebookPath (see EditRulebookSh's RULEBOOK_SELF_UPDATE_PATH) -- the real
# basename of the project's rulebook file, e.g. "effortless-banking-rulebook.json".
# It is NOT hardcoded to "effortless-rulebook.json" here, because that name is
# only one of two valid conventions (the other being "<slug>-rulebook.json" --
# see the platform rulebook's ProjectLayoutSlots). A hardcoded guess that
# disagreed with the actual mounted filename used to make EVERY pipeline step
# fail with "No INPUT files matched" -- silently, since `effortless build`
# keeps going after a failed step -- while the container still reported
# itself as running. Fail loudly here instead, before anything else runs.
# BOOT_STATE_FILE/BUILD_LOG_FILE are defined immediately above, before this
# check, specifically so this FATAL path can write to them under `set -u`
# instead of dying on an unbound-variable error and hiding the real message.
if [ -z "${RULEBOOK_FILENAME:-}" ]; then
  echo "[entrypoint] FATAL: RULEBOOK_FILENAME was not set." >&2
  {
    echo "[entrypoint] $(date -Iseconds) FATAL: RULEBOOK_FILENAME environment variable is required and was not passed to this container."
    echo "[entrypoint]   This should always be set automatically by edit-rulebook.sh's \`docker run -e RULEBOOK_FILENAME=...\`."
    echo "[entrypoint]   FIX: relaunch via ./edit-rulebook.sh (regenerate it first with \`effortless effortless-rulebook-editor\` if it predates this variable)."
    echo "[entrypoint]   If you are invoking \`docker run\` by hand, add:  -e RULEBOOK_FILENAME=<your-rulebook>.json"
    echo "[entrypoint]   (the exact filename inside the mounted effortless-rulebook/ folder, e.g. effortless-banking-rulebook.json)."
    echo "[entrypoint] Refusing to guess a filename and build against the wrong file. Exiting instead of retry-looping."
  } | tee -a "$BUILD_LOG_FILE" >&2
  echo "error" > "$BOOT_STATE_FILE"
  sleep 2
  exit 1
fi
RULEBOOK_PATH="/app/effortless-rulebook/$RULEBOOK_FILENAME"
RULEBOOK_DIR="/app/effortless-rulebook"
# Where the effortless CLI writes its structured build-failure record when
# -continueOnError is in effect (see BuildErrorLog in the CLI): the project root,
# which for this container is always the effortless-root symlink target. Its mere
# EXISTENCE is the contract -- present means the last build had failures, absent
# means it was clean. Copied to BOOT_ERRORS_FILE so boot-server.js can serve it
# from a fixed path without knowing where effortless-root actually resolved to.
ERRORS_JSON_PATH="/app/effortless-root/errors.json"
BOOT_ERRORS_FILE="/tmp/build-errors.json"
# Component-level health snapshot written after every build (see
# write_status_json below), served as GET /__boot/status. This is what makes
# "which parts of this container are alive?" answerable when most of them aren't.
BOOT_STATUS_FILE="/tmp/boot-status.json"
# The declared build pipeline (effortless.json's ProjectTranspilers), seeded onto
# disk further down BEFORE the first build runs. Served as GET /__boot/pipeline so
# the boot page can show the whole sequence -- and what each step is for -- from the
# moment the container starts, instead of revealing steps only as they scroll past.
# Addressed through the /app/effortless-root symlink deliberately: that link is
# created below, after boot-server.js has already started, and boot-server reads
# this path per request rather than at startup.
BOOT_PIPELINE_FILE="/app/effortless-root/effortless.json"
# Build-gating on pending uncommitted changes (see check_uncommitted_before_build
# below). CONFLICT_CHOICE_FILE is the signal file boot-server.js's new
# POST /__boot/resolve-conflict route writes to, following the exact same
# poll-a-fixed-path pattern already used for BOOT_STATE_FILE/REBUILD_TRIGGER_FILE
# above -- no new IPC mechanism invented for this.
CONFLICT_CHOICE_FILE="/tmp/conflict-choice"
# The rebuild OFFER made when the rulebook file changes on disk (see
# prompt_for_rebuild below). Same poll-a-fixed-path pattern as everything else
# here: the entrypoint writes REBUILD_PROMPT_FILE (containing the epoch second
# the offer expires) and waits; boot-server.js reads it to answer
# GET /__boot/rebuild-prompt, and writes one of the two answer files when the
# user clicks Rebuild now / Not now in the app.
REBUILD_PROMPT_FILE="/tmp/rebuild-prompt"
REBUILD_PROMPT_CONFIRM_FILE="/tmp/rebuild-prompt-confirm"
REBUILD_PROMPT_DISMISS_FILE="/tmp/rebuild-prompt-dismiss"
REBUILD_PROMPT_TIMEOUT_SECS=45
# Touched by the generated API immediately before IT writes the rulebook file
# (see uncommitted.js's mergeUncommittedIntoRulebook). A rulebook change that
# lands within SELF_WRITE_GRACE_SECS of this marker is the app's OWN Save, not
# somebody editing the file behind the app's back -- and there is nothing to
# ask about, because Save leaves Postgres already matching the rulebook. Without
# this, every Save popped a "the rulebook changed, rebuild?" toast, and with
# auto-save switched on it would pop one every few edits.
SELF_WRITE_MARKER_FILE="/tmp/rulebook-self-write"
SELF_WRITE_GRACE_SECS=10
# Auto-save setting file, written by the generated API's
# PATCH /api/admin/auto-save-setting (uncommitted.js owns the path convention:
# a sibling of the rulebook named <base>.editor-settings.json). Read here so a
# rebuild only folds pending edits into the rulebook on the user's behalf when
# they actually asked for that -- see check_uncommitted_before_build.
EDITOR_SETTINGS_FILE="$RULEBOOK_DIR/$(basename "$RULEBOOK_PATH" .json).editor-settings.json"
# Port the generated Node API listens on -- same value start_services() below
# already uses (PORT=5177). Needed here too so the "overwrite" resolution can
# curl the API's own /api/save-changes merge endpoint directly, when that
# instance of the API is still up and reachable (see the caveat in that
# function).
API_PORT=5177
API_PID=""
UI_PID=""
BOOT_SERVER_PID=""

echo "booting" > "$BOOT_STATE_FILE"
touch "$BUILD_LOG_FILE" "$REBUILD_TRIGGER_FILE"
rm -f "$CONFLICT_CHOICE_FILE" "$REBUILD_PROMPT_FILE" "$REBUILD_PROMPT_CONFIRM_FILE" "$REBUILD_PROMPT_DISMISS_FILE"

echo "[entrypoint] starting boot-server.js on :5174 (immediate progress page + log stream + rebuild button)..."
BOOT_LOG_FILE="$BUILD_LOG_FILE" BOOT_STATE_FILE="$BOOT_STATE_FILE" BOOT_REBUILD_TRIGGER="$REBUILD_TRIGGER_FILE" \
BOOT_CONFLICT_CHOICE_FILE="$CONFLICT_CHOICE_FILE" \
BOOT_REBUILD_PROMPT_FILE="$REBUILD_PROMPT_FILE" \
BOOT_REBUILD_PROMPT_CONFIRM_FILE="$REBUILD_PROMPT_CONFIRM_FILE" \
BOOT_REBUILD_PROMPT_DISMISS_FILE="$REBUILD_PROMPT_DISMISS_FILE" \
BOOT_ERRORS_FILE="$BOOT_ERRORS_FILE" \
BOOT_STATUS_FILE="$BOOT_STATUS_FILE" \
BOOT_PIPELINE_FILE="$BOOT_PIPELINE_FILE" \
  node /app/boot-server.js > /tmp/boot-server.log 2>&1 &
BOOT_SERVER_PID=$!

# The host's ~/.ssotme is bind-mounted READ-ONLY at /root/.ssotme-ro (auth
# credentials live there and must never be mutated from inside the
# container). The effortless CLI needs a writable HOME/CLI state directory,
# so we copy the read-only mount into a writable working copy at
# /root/.ssotme once at startup and point HOME/CLI state there instead. The
# host's real ~/.ssotme is never touched.
if [ -d /root/.ssotme-ro ]; then
  echo "[entrypoint] copying read-only ~/.ssotme mount into a writable working copy..."
  rm -rf /root/.ssotme
  cp -r /root/.ssotme-ro /root/.ssotme
  chmod -R u+w /root/.ssotme
fi

# /app/effortless-root is a symlink to wherever effortless.json + every file
# `effortless build` generates (api/, admin-portal/, postgres/, rulespeak/,
# xlsx/) actually live. Two possible targets, chosen once here at boot:
#   - /app/effortless-editor-tmp/effortless-editor-src (host-backed, survives
#     restarts/rebuilds) when edit-rulebook.sh mounted a tempDir -- see
#     EFFORTLESS_EDITOR_TEMPDIR_MOUNTED, set by that script's docker run -e.
#   - /app/effortless-root-internal (container-only, does NOT survive a
#     container recreate -- only a plain restart) otherwise.
# Everything below this point (the build, the RULEBOOK_PATH existence check
# is unaffected -- that stays under the separate rulebook mount) operates
# through /app/effortless-root, never through either real target directly, so
# the rest of this script does not need to know which case it's in.
if [ -n "${EFFORTLESS_EDITOR_TEMPDIR_MOUNTED:-}" ]; then
  EFFORTLESS_ROOT_TARGET="/app/effortless-editor-tmp/effortless-editor-src"
else
  EFFORTLESS_ROOT_TARGET="/app/effortless-root-internal"
fi
mkdir -p "$EFFORTLESS_ROOT_TARGET"
ln -sfn "$EFFORTLESS_ROOT_TARGET" /app/effortless-root

# Make the bind-mounted rulebook reachable from INSIDE the build root.
#
# Every step in effortless.editor.json addresses the rulebook the same way --
# `-i ../effortless-rulebook/$RULEBOOK_FILENAME` (the seed step below rewrites
# the placeholder filename to the real one), relative to its own RelativePath
# (/postgres, /api, /admin-portal, ...) -- which resolves to
# $EFFORTLESS_ROOT_TARGET/effortless-rulebook. The rulebook is mounted
# somewhere else entirely (/app/effortless-rulebook), so without this link
# nothing in the pipeline can see it: `effortless build` reports one
# easy-to-miss "No INPUT files matched" warning per step and
# rulebook-to-postgres fails outright with "No rulebook JSON provided". (That
# was exactly the state after the build root moved out of /app -- back when
# the build ran with `cd /app`, ../effortless-rulebook happened to land on the
# mount, and the link was not needed.)
#
# A symlink rather than a copy, deliberately: the API and the merge path write
# the real rulebook file and its uncommitted-change log through
# /app/effortless-rulebook, and those writes have to land on the host mount,
# not on a stale duplicate.
ln -sfn /app/effortless-rulebook "$EFFORTLESS_ROOT_TARGET/effortless-rulebook"

# Seed effortless.json ONLY if missing -- this is what makes everything
# `effortless build` generates under /app/effortless-root (SQL, the Node API,
# the Vite UI, RuleSpeak®, XLSX export) STATIC/editable across rebuilds by
# default: a rebuild re-runs `effortless build` against whatever's already
# there, it does NOT reset effortless.json (or therefore the pipeline it
# describes) back to the tool's shipped default on every boot. To reset to
# the shipped default, remove effortless.json from the target above (or the
# whole tempDir, when host-backed) and restart.
if [ ! -f "$EFFORTLESS_ROOT_TARGET/effortless.json" ]; then
  echo "[entrypoint] seeding $EFFORTLESS_ROOT_TARGET/effortless.json (first boot, or a reset) from the tool's default pipeline config..."
  cp /app/effortless.editor.json.seed "$EFFORTLESS_ROOT_TARGET/effortless.json"

  # The seed's every -i flag hardcodes the placeholder "effortless-rulebook.json"
  # (see EffortlessEditorJson -- it is baked into the image and cannot know any
  # project's real filename). Substitute the actual mounted filename now, once,
  # at seed time only -- NOT on every boot, so a user's own hand-edited pipeline
  # steps are never touched again after this first pass. If the placeholder is
  # ever not found (e.g. a future image ships a differently-worded seed), fail
  # loudly rather than silently leaving every step pointed at the wrong file.
  if ! grep -q "effortless-rulebook/effortless-rulebook.json" "$EFFORTLESS_ROOT_TARGET/effortless.json"; then
    echo "[entrypoint] FATAL: expected placeholder 'effortless-rulebook/effortless-rulebook.json' not found in the freshly-seeded effortless.json." >&2
    echo "[entrypoint]   The seed template may have changed shape. Cannot safely substitute the real rulebook filename ($RULEBOOK_FILENAME)." >&2
    echo "error" > "$BOOT_STATE_FILE"
    exit 1
  fi
  sed -i "s#effortless-rulebook/effortless-rulebook\.json#effortless-rulebook/$RULEBOOK_FILENAME#g" "$EFFORTLESS_ROOT_TARGET/effortless.json"
  echo "[entrypoint] pointed the seeded pipeline's -i flags at effortless-rulebook/$RULEBOOK_FILENAME"
fi

# Versioned migrations for pipeline DEFAULTS, not per-build overrides.
# Existing host-backed build roots retain their effortless.json across image
# upgrades, so changing only the seed never reaches them.
#
# Version 2: English-only/no-XLSX -> all RuleSpeak® languages plus XLSX.
# Version 3: init-db.sh -> the compatibility reset wrapper, because current
#            rulebook-to-postgres emits reset-rulebook-db.sh.
# Version 4: pin -p mode=check-add on the Postgres step, so a rebuild of a
#            running container adds tables/columns and upserts rows instead
#            of dropping and reseeding whatever the user has in the editor.
#
# Each migration changes only its exact prior default. Any other value is an
# intentional user customization and is preserved.
# Version 6: the ERB module steps (rulebook-to-rbac, the Postgres policy
#            compiler, the progress report) are added, disabled; the portal's
#            Modules page switches them on with their module.
# Version 7: the Explainer DAG step bakes RuleSpeak® in every registered
#            language (-p languages=all), so the Provenance tab's hover cards
#            and field pages follow the portal's language instead of English.
PIPELINE_DEFAULTS_VERSION=7
if ! node - "$EFFORTLESS_ROOT_TARGET/effortless.json" "$PIPELINE_DEFAULTS_VERSION" <<'NODE'
const fs = require('fs');
const file = process.argv[2];
const targetVersion = Number(process.argv[3]);
const cfg = JSON.parse(fs.readFileSync(file, 'utf8'));
const settings = Array.isArray(cfg.ProjectSettings) ? cfg.ProjectSettings : (cfg.ProjectSettings = []);
let marker = settings.find((s) => s && s.Name === 'editor-pipeline-defaults-version');
const currentVersion = Number(marker && marker.Value) || 0;

if (currentVersion < targetVersion) {
  const steps = Array.isArray(cfg.ProjectTranspilers) ? cfg.ProjectTranspilers : [];
  const byName = new Map(steps.map((s) => [s.Name, s]));

  if (currentVersion < 2) {
    const english = byName.get('rulebooktorulespeaken');
    const allLanguages = byName.get('rulebooktorulespeak');
    const xlsx = byName.get('rulebooktoxlsx');
    if (!english || !allLanguages || !xlsx) {
      throw new Error('pipeline defaults v2 migration requires the English, all-languages, and XLSX steps');
    }

    const isLegacyDefault =
      english.IsDisabled === false &&
      allLanguages.IsDisabled === true &&
      xlsx.IsDisabled === true;
    if (isLegacyDefault) {
      english.IsDisabled = true;
      allLanguages.IsDisabled = false;
      xlsx.IsDisabled = false;
      console.log('[entrypoint] migrated legacy build defaults: all RuleSpeak languages + XLSX are enabled');
    } else {
      console.log('[entrypoint] preserved customized build-step choices while advancing defaults to v2');
    }
  }

  if (currentVersion < 3) {
    const initDb = byName.get('initdb');
    if (!initDb) {
      throw new Error('pipeline defaults v3 migration requires the initdb step');
    }

    if (initDb.CommandLine === '-exec ./init-db.sh') {
      initDb.CommandLine = '-exec ./run-rulebook-db-reset.sh';
      initDb.Description = 'Reset the in-container Postgres DB using reset-rulebook-db.sh when present, with legacy init-db.sh compatibility for older rulebook-to-postgres versions.';
      console.log('[entrypoint] migrated database reset step to the current filename with legacy compatibility');
    } else if (initDb.CommandLine !== '-exec ./run-rulebook-db-reset.sh') {
      console.log('[entrypoint] preserved customized initdb command while advancing defaults to v3');
    }
  }

  if (currentVersion < 4) {
    const postgres = byName.get('rulebooktopostgres');
    if (!postgres) {
      throw new Error('pipeline defaults v4 migration requires the rulebooktopostgres step');
    }

    // Matched by prefix, not by equality: the -i flag was rewritten to this
    // project's real rulebook filename when effortless.json was seeded, so
    // there is no single expected string to compare against. An explicit
    // mode= of any value is the user's choice and is left alone.
    const command = String(postgres.CommandLine || '');
    if (command.startsWith('rulebook-to-postgres ') && !/(^|\s)-p\s+mode=/.test(command)) {
      postgres.CommandLine = command + ' -p mode=check-add';
      console.log('[entrypoint] pinned mode=check-add on the Postgres step: rebuilds of a running container now add tables/columns and upsert rows instead of reseeding from scratch');
    } else {
      console.log('[entrypoint] preserved customized Postgres command while advancing defaults to v4');
    }
  }

  if (currentVersion < 5) {
    // The former all-languages default becomes a focused four-language default,
    // and 'every language' moves to its own step the portal can switch on. Only
    // the untouched former default is rewritten -- a hand-edited languages= list
    // is the user's choice and survives.
    const core = byName.get('rulebooktorulespeak');
    if (!core) {
      throw new Error('pipeline defaults v5 migration requires the rulebooktorulespeak step');
    }

    const command = String(core.CommandLine || '');
    if (/(^|\s)-p\s+languages=all(\s|$)/.test(command)) {
      core.CommandLine = command.replace(/((^|\s)-p\s+languages=)all(\s|$)/, '$1en,de,ja,hi$3');
      console.log('[entrypoint] narrowed the default RuleSpeak build to en,de,ja,hi; every-language builds now live on their own step');
    } else {
      console.log('[entrypoint] preserved customized RuleSpeak languages while advancing defaults to v5');
    }

    if (!byName.get('rulebooktorulespeakall')) {
      const at = steps.indexOf(core);
      steps.splice(at + 1, 0, {
        IsSSoTTranspiler: false,
        Name: 'rulebooktorulespeakall',
        RelativePath: core.RelativePath,
        CommandLine: command.replace(/((^|\s)-p\s+languages=)[^\s]+/, '$1all'),
        IsDisabled: true,
        Description: 'Generate the RuleSpeak® document in EVERY registered language. Disabled by default; the portal\'s language picker turns this on (and the core-languages step off) when someone asks for the remaining languages.',
      });
      console.log('[entrypoint] added the every-language RuleSpeak step (disabled by default)');
    }
  }

  if (currentVersion < 6) {
    const rb = '../effortless-rulebook/effortless-rulebook.json';
    const inputOf = (step) => {
      const m = String((step && step.CommandLine) || '').match(/-i\s+(\S+)/);
      return m ? m[1] : rb;
    };
    const postgres = byName.get('rulebooktopostgres');
    if (!byName.get('rulebooktorbac') && postgres) {
      const at = steps.indexOf(postgres);
      steps.splice(at + 1, 0, {
        IsSSoTTranspiler: false,
        Name: 'rulebooktorbac',
        RelativePath: '/rbac',
        CommandLine: 'rulebook-to-rbac -i ' + inputOf(postgres),
        IsDisabled: true,
        Description: 'Security module: read the ERBRoles / ERBUsers / permission tables and emit rbac/effortless-rbac.json, the database-neutral role model the policy generators compile. Disabled until the Security module is switched on in the portal\'s Modules page.',
      }, {
        IsSSoTTranspiler: false,
        Name: 'rbactopostgrespolicies',
        RelativePath: '/postgres',
        CommandLine: 'effortless-rbac-to-postgres-policies -i ../rbac/effortless-rbac.json',
        IsDisabled: true,
        Description: 'Security module: compile rbac/effortless-rbac.json into postgres/06-rbac-policies.sql -- roles, grants, row-level security, identity helpers, one schema per role. Applied by the database reset step after the data. Disabled until the Security module is on.',
      });
      console.log('[entrypoint] added the Security module build steps (disabled by default)');
    }
    if (!byName.get('rulebooktoprogressreport')) {
      steps.push({
        IsSSoTTranspiler: false,
        Name: 'rulebooktoprogressreport',
        RelativePath: '/progress-report',
        CommandLine: 'rulebook-to-progress-report -i ' + inputOf(postgres),
        IsDisabled: true,
        Description: 'Delivery module: render the Progress Report from the ERBUserStories / ERBAcceptanceCriteria / ERBBuildPhases tables, shown under the portal\'s Progress Report tab. Disabled until the Delivery module is switched on.',
      });
      console.log('[entrypoint] added the Delivery module build step (disabled by default)');
    }
  }

  if (currentVersion < 7) {
    // The Explainer DAG step used to bake RuleSpeak in English only, so its hover
    // cards stayed English whatever the portal language. Only the untouched former
    // default (no languages= at all) is rewritten; an explicit list survives.
    const explainer = byName.get('rulebooktoexplainerdag');
    const command = String((explainer && explainer.CommandLine) || '');
    if (command.startsWith('rulebook-to-explainer-dag ') && !/(^|\s)-p\s+languages?=/.test(command)) {
      explainer.CommandLine = command + ' -p languages=all';
      console.log('[entrypoint] the Explainer DAG step now bakes every RuleSpeak language, so provenance cards follow the portal language');
    } else {
      console.log('[entrypoint] preserved customized Explainer DAG command while advancing defaults to v7');
    }
  }

  if (marker) marker.Value = String(targetVersion);
  else settings.push({ Name: 'editor-pipeline-defaults-version', Value: String(targetVersion) });
  const tmp = file + '.tmp-defaults';
  fs.writeFileSync(tmp, JSON.stringify(cfg, null, 2) + '\n');
  fs.renameSync(tmp, file);
}
NODE
then
  echo "[entrypoint] FATAL: could not migrate the editor pipeline defaults." >&2
  echo "error" > "$BOOT_STATE_FILE"
  exit 1
fi

# ERB modules: a rulebook that arrives with a module already switched on
# (_meta.erb.modules.<name>.enabled) gets that module's build steps switched
# on BEFORE the first build, so the very first boot compiles its policies /
# report rather than waiting for the generated API to notice and a rebuild.
# Mirrors the module->steps table in the API's erb-schema.js.
if [ -f "$RULEBOOK_PATH" ]; then
  node - "$EFFORTLESS_ROOT_TARGET/effortless.json" "$RULEBOOK_PATH" <<'NODE' || echo "[entrypoint] warning: could not reconcile ERB module build steps (continuing)"
const fs = require('fs');
const [file, rulebookPath] = process.argv.slice(2);
const MODULE_STEPS = {
  security: ['rulebooktorbac', 'rbactopostgrespolicies', 'rbactosqlserverpolicies'],
  delivery: ['rulebooktoprogressreport'],
};
let modules = {};
try { modules = (JSON.parse(fs.readFileSync(rulebookPath, 'utf8'))._meta || {}).erb?.modules || {}; } catch { process.exit(0); }
const cfg = JSON.parse(fs.readFileSync(file, 'utf8'));
const steps = Array.isArray(cfg.ProjectTranspilers) ? cfg.ProjectTranspilers : [];
const switched = [];
for (const [name, list] of Object.entries(MODULE_STEPS)) {
  if (modules[name]?.enabled !== true) continue;
  for (const step of steps) if (list.includes(step.Name) && step.IsDisabled === true) { step.IsDisabled = false; switched.push(step.Name); }
}
if (switched.length) {
  const tmp = file + '.tmp-modules';
  fs.writeFileSync(tmp, JSON.stringify(cfg, null, 2) + '\n');
  fs.renameSync(tmp, file);
  console.log('[entrypoint] ERB modules already on in the rulebook: switched on build steps ' + switched.join(', '));
}
NODE
fi

# Fail loudly, immediately, if the project's effortless-rulebook/ folder was
# not actually bind-mounted to $RULEBOOK_DIR. Without this check, `effortless
# build` runs against a missing/empty directory, every transpiler step prints
# one easy-to-miss "No INPUT files matched" warning buried in its own output,
# and the container reports READY STATE: NOT READY -- which looks like normal
# build-failure output. Then the file-watch loop further down starts calling
# inotifywait against a path that doesn't exist, which errors out instantly
# every time, and (before this fix) that instant error was indistinguishable
# from a real file-change event -- so the container silently rebuilt itself
# in an infinite loop instead of ever surfacing the actual problem. A common
# cause on Windows Git Bash: MSYS path auto-conversion mangling the `docker
# run -v` bind-mount flag (see edit-rulebook.sh's MSYS_NO_PATHCONV handling).
if [ ! -d "$RULEBOOK_DIR" ] || [ ! -f "$RULEBOOK_PATH" ]; then
  echo "[entrypoint] FATAL: $RULEBOOK_PATH not found inside the container." >&2
  {
    echo "[entrypoint] $(date -Iseconds) FATAL: the project's effortless-rulebook/ folder is not correctly bind-mounted, OR RULEBOOK_FILENAME ($RULEBOOK_FILENAME) does not match the actual mounted file."
    echo "[entrypoint]   Expected to find: $RULEBOOK_PATH"
    echo "[entrypoint]   RULEBOOK_DIR exists: $([ -d "$RULEBOOK_DIR" ] && echo yes || echo NO)"
    echo "[entrypoint]   Contents of $RULEBOOK_DIR (if mounted):"
    ls -la "$RULEBOOK_DIR" 2>&1 | sed 's/^/[entrypoint]     /'
    echo "[entrypoint]   Contents of /app:"
    ls -la /app 2>&1 | sed 's/^/[entrypoint]     /'
    echo "[entrypoint]   If the folder above IS mounted but under a DIFFERENT filename than $RULEBOOK_FILENAME:"
    echo "[entrypoint]     re-run \`effortless effortless-rulebook-editor -p rulebookPath=../effortless-rulebook/<actual-name>.json\`"
    echo "[entrypoint]     to regenerate edit-rulebook.sh with the correct RULEBOOK_FILENAME, then relaunch it."
    echo "[entrypoint]   If the folder is not mounted at all: check the docker run -v flag (see edit-rulebook.sh) actually"
    echo "[entrypoint]   mounted the host effortless-rulebook/ folder to $RULEBOOK_DIR -- on Windows Git Bash, MSYS path"
    echo "[entrypoint]   auto-conversion is a common cause of a bind mount silently landing somewhere else."
    echo "[entrypoint] Refusing to build or watch a missing/mismatched mount. Exiting instead of retry-looping."
  } | tee -a "$BUILD_LOG_FILE" >&2
  echo "error" > "$BOOT_STATE_FILE"
  sleep 2
  exit 1
fi

# Does THIS image's effortless CLI understand -continueOnError?
#
# The Dockerfile installs the CLI with `git clone --depth 1 <cli repo>` at
# IMAGE-BUILD time, so the CLI version inside any given image is whatever main
# happened to be that day -- it is NOT pinned to this tool's version. Passing an
# option an older CLI has never heard of makes its argument parser reject the
# whole command, which would turn "tolerate a failing step" into "fail every
# build outright" -- the exact opposite of the point. So: probe once, here, and
# degrade to the old behavior with a loud warning rather than breaking.
CONTINUE_ON_ERROR_FLAG=""
# The CLI's BARE `-help` prints only the top-level meta/project/build/clean
# summary and never lists -continueOnError -- only `-help all` (or `-help
# build`) does. Probing bare `-help` always misses it on every current CLI
# version, silently falling back to "no flag" and defeating the entire point
# of this probe: one failing transpiler would abort the whole build with no
# warning that anything was wrong. `-help all` is the one topic guaranteed to
# list every option regardless of category, so it is the only reliable probe.
if effortless -help all 2>/dev/null | grep -q -- "-continueOnError"; then
  CONTINUE_ON_ERROR_FLAG="-continueOnError"
else
  echo "[entrypoint] WARNING: this image's effortless CLI predates -continueOnError."
  echo "[entrypoint]          A single failing transpiler will abort the whole build and"
  echo "[entrypoint]          the API/portal may not start. Rebuild the image"
  echo "[entrypoint]          (./edit-rulebook.sh --rebuild) to pick up a newer CLI."
fi

echo "[entrypoint] starting local Postgres cluster..."
mkdir -p /var/lib/postgresql/data
chown -R postgres:postgres /var/lib/postgresql
if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
  su postgres -c "/usr/lib/postgresql/*/bin/initdb -D /var/lib/postgresql/data" >/tmp/initdb.log 2>&1
fi
# initdb's default pg_hba.conf only trusts 127.0.0.1/::1 -- a host client
# connecting through the published -p 5432 port arrives via Docker Desktop's
# host-forwarding proxy, which does NOT present a Docker-internal bridge
# address (varies by platform), so a scoped rule can't reliably match. This
# is a container-local dev DB, rebuilt from scratch on every container start,
# behind the user's own firewall -- open trust to any host is fine here.
if ! grep -q "0.0.0.0/0" /var/lib/postgresql/data/pg_hba.conf 2>/dev/null; then
  echo "host    all             all             0.0.0.0/0               trust" >> /var/lib/postgresql/data/pg_hba.conf
  echo "host    all             all             ::/0                    trust" >> /var/lib/postgresql/data/pg_hba.conf
fi
su postgres -c "/usr/lib/postgresql/*/bin/pg_ctl -D /var/lib/postgresql/data -l /tmp/postgres.log -o '-h 0.0.0.0' start"

echo "[entrypoint] waiting for Postgres to accept connections..."
for i in $(seq 1 60); do
  su postgres -c "psql -c 'select 1' >/dev/null 2>&1" && break
  sleep 1
done

# Ensure the app role + database exist (idempotent -- safe on restart loops).
su postgres -c "psql -c \"ALTER USER postgres PASSWORD 'postgres';\" " >/dev/null 2>&1
su postgres -c "createdb effortless-rulebook" >/dev/null 2>&1 || true

export PGHOST=localhost
export PGPORT=5432
export PGUSER=postgres
export PGPASSWORD=postgres
export PGDATABASE=effortless-rulebook
export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/effortless-rulebook"

# The CLI's -exec form accepts one command token and cannot express shell
# conditionals. These two no-args wrappers give the pipeline a stable command:
# prepare makes generated scripts executable, then run selects the current
# reset-rulebook-db.sh filename and uses init-db.sh only for an older
# rulebook-to-postgres version.
#
# The run wrapper is also where this container's data-safety rule lives, so
# read the comments inside it before changing the initdb step.
#
# Both wrappers are written before every build because rulebook-to-postgres
# creates the postgres directory during the first build.
mkdir -p /app/effortless-root/postgres
cat > /app/effortless-root/postgres/chmod-initdb.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
chmod +x "$SCRIPT_DIR/run-rulebook-db-reset.sh"
[ ! -f "$SCRIPT_DIR/reset-rulebook-db.sh" ] || chmod +x "$SCRIPT_DIR/reset-rulebook-db.sh"
[ ! -f "$SCRIPT_DIR/init-db.sh" ] || chmod +x "$SCRIPT_DIR/init-db.sh"
EOF
cat > /app/effortless-root/postgres/run-rulebook-db-reset.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Which filename does the installed rulebook-to-postgres emit?
if [ -f "$SCRIPT_DIR/reset-rulebook-db.sh" ]; then
  DB_APPLY_SCRIPT="$SCRIPT_DIR/reset-rulebook-db.sh"
elif [ -f "$SCRIPT_DIR/init-db.sh" ]; then
  echo "[db-apply] reset-rulebook-db.sh not found; using legacy init-db.sh" >&2
  DB_APPLY_SCRIPT="$SCRIPT_DIR/init-db.sh"
else
  echo "[db-apply] no database apply script found; expected reset-rulebook-db.sh or legacy init-db.sh" >&2
  exit 127
fi

# ------------------------------------------------------------------------
# The first apply in this container's life is a build from scratch. Every
# apply after it must be additive.
#
# The Postgres cluster lives inside the container with no volume, so it is
# always empty at boot -- the first apply has nothing to preserve and the
# from-scratch build is free. Every rebuild after that runs while somebody
# has the editor open, with rows they added through the UI and edits not yet
# saved back to the rulebook. Those must survive: a rulebook change should
# add the new tables and columns, upsert the rulebook's own rows, and leave
# everything else exactly where it is.
#
# rulebook-to-postgres already generates that shape in its default
# mode=check-add (CREATE TABLE IF NOT EXISTS, ADD COLUMN IF NOT EXISTS,
# CREATE OR REPLACE for the derived layer, ON CONFLICT DO UPDATE for rows),
# and the rulebooktopostgres step pins mode=check-add so this does not
# depend on a default that lives in another tool. The block below is the
# check that it actually held.
#
# On a violation this REFUSES the step. It does not fall back to applying
# some safer-looking subset: half-applied SQL against a live editor is a
# worse outcome than a build step that stops and says which file would have
# destroyed data.
# ------------------------------------------------------------------------
STAMP_FILE="${EFFORTLESS_EDITOR_DB_STAMP:-/tmp/rulebook-db-applied}"

if [ ! -f "$STAMP_FILE" ]; then
  echo "[db-apply] first apply for this container -- building the database from scratch"
elif [ "${EFFORTLESS_EDITOR_ALLOW_DB_RESET:-}" = "1" ]; then
  echo "[db-apply] EFFORTLESS_EDITOR_ALLOW_DB_RESET=1 -- destructive SQL allowed on this rebuild"
else
  OFFENDING_FILES=""
  shopt -s nullglob
  for sql_file in "$SCRIPT_DIR"/[0-9][0-9]*-*.sql; do
    # Comments come off first: 00-bootstrap.sql ships an inert, commented-out
    # drop-everything block that must not trip this.
    #
    # pipefail is off inside the subshell on purpose. grep -q exits at its
    # first match, sed then dies of SIGPIPE, and pipefail would report that
    # as "no match" -- turning the guard into a silent no-op.
    if ( set +o pipefail; sed 's/--.*$//' "$sql_file" \
         | grep -qiE '(DROP[[:space:]]+(TABLE|SCHEMA|DATABASE)|TRUNCATE[[:space:]]|DELETE[[:space:]]+FROM)' ); then
      OFFENDING_FILES="$OFFENDING_FILES $(basename "$sql_file")"
    fi
  done
  if [ -n "$OFFENDING_FILES" ]; then
    echo "[db-apply] REFUSING to apply: this rebuild would destroy data in a running editor." >&2
    echo "[db-apply]   offending file(s):$OFFENDING_FILES" >&2
    echo "[db-apply] While the container is up, a rebuild is additive only. The usual cause" >&2
    echo "[db-apply] is the rulebooktopostgres step in effortless.json having lost its" >&2
    echo "[db-apply] '-p mode=check-add' (mode=drop-all generates DROP TABLE), or a" >&2
    echo "[db-apply] hand-written NNb-customize-*.sql that drops or deletes." >&2
    echo "[db-apply] To wipe on purpose: restart the container -- the DB is built from" >&2
    echo "[db-apply] scratch on every boot -- or set EFFORTLESS_EDITOR_ALLOW_DB_RESET=1." >&2
    exit 1
  fi
  echo "[db-apply] rebuild while running -- applying additively (new tables/columns, upserted rows)"
fi

# Not exec'd: the stamp is only written once the apply has actually succeeded,
# so a build that dies before the SQL lands is still treated as the first one.
"$DB_APPLY_SCRIPT"
touch "$STAMP_FILE"
EOF
chmod +x \
  /app/effortless-root/postgres/chmod-initdb.sh \
  /app/effortless-root/postgres/run-rulebook-db-reset.sh


check_uncommitted_before_build() {
  # Gate on pending uncommitted-changes log file(s) before any build EXCEPT
  # the very first one at container boot (nothing can be pending yet -- the
  # generated Node API hasn't even started). Called from the watch loop
  # below, never from the first `run_build` at the bottom of this script.
  #
  # Pending files follow the SAME naming convention the generated Node API's
  # uncommitted.js uses (see rulebook-to-node-postgres-api): sibling of the
  # rulebook file, "<rulebookBaseName>.uncommitted-NN.json". We only need to
  # detect them here, not parse/merge them ourselves -- merging is the Node
  # API's job (mergeUncommittedIntoRulebook(), reused as-is by option 3 below).
  local base
  base="$(basename "$RULEBOOK_PATH" .json)"
  local pending
  pending=$(ls "$RULEBOOK_DIR"/${base}.uncommitted-*.json 2>/dev/null || true)
  if [ -z "$pending" ]; then
    return 0
  fi

  # The three-way conflict prompt below is disabled: in practice it fired on
  # essentially every Save, because Save itself writes the rulebook file (to
  # merge the pending log into it) and that write trips this very watcher --
  # the build gated against the pending file that the in-flight Save had not
  # finished consuming yet. So Save conflicted with itself, the rebuild blocked
  # on a prompt nobody asked for, and the edits ended up in a
  # merge-conflict-*.json instead of the rulebook.
  #
  # What replaces it depends on the AUTO-SAVE setting (Admin page -> Build):
  #
  #   auto-save ON  -- writing pending edits into the rulebook without being
  #     asked is exactly what the user turned on, so merge them (reusing the
  #     Node API's own mergeUncommittedIntoRulebook via POST /api/save-changes)
  #     and build.
  #
  #   auto-save OFF (default) -- the user has NOT saved these edits, and this
  #     build would push the rulebook back over the top of them in Postgres.
  #     Silently merging would be an auto-save they explicitly declined, so the
  #     pending log is LEFT EXACTLY WHERE IT IS and the build proceeds. Nothing
  #     is lost: the log survives the rebuild, so Save Changes still applies
  #     those edits afterwards (and Discard Changes still throws them away).
  #
  # Either way the pending file is never moved aside or deleted here.
  echo "[entrypoint] $(date -Iseconds) pending uncommitted changes found before this build:" >> "$BUILD_LOG_FILE"
  echo "$pending" | sed 's/^/[entrypoint]   /' >> "$BUILD_LOG_FILE"

  if grep -q '"autoSaveEnabled"[[:space:]]*:[[:space:]]*true' "$EDITOR_SETTINGS_FILE" 2>/dev/null; then
    echo "[entrypoint] auto-save is ON -- merging pending change(s) into the rulebook before building." >> "$BUILD_LOG_FILE"
    if curl -sf -X POST "http://127.0.0.1:${API_PORT}/api/save-changes" >/dev/null 2>&1; then
      echo "[entrypoint] merged pending change(s) into the rulebook." >> "$BUILD_LOG_FILE"
    else
      echo "[entrypoint] API not reachable to merge; leaving pending file(s) in place for the next Save." >> "$BUILD_LOG_FILE"
    fi
  else
    echo "[entrypoint] auto-save is OFF -- NOT writing these edits into the rulebook. They stay pending; click Save Changes to keep them, or Discard Changes to drop them." >> "$BUILD_LOG_FILE"
  fi
  return 0
}

# Offer a rebuild and wait for an answer. Returns 0 (rebuild) only on an
# explicit confirmation; returns 1 on an explicit dismissal OR on timeout.
#
# BOOT_STATE_FILE is deliberately NOT touched here. Any state other than
# "ready" makes boot-server.js stop proxying and serve its own boot page
# instead -- which would yank the user out of the app they are working in just
# to ask them a question. The whole point is a toast INSIDE the running app, so
# the app must stay up and proxied while the offer stands.
prompt_for_rebuild() {
  local deadline
  deadline=$(( $(date +%s) + REBUILD_PROMPT_TIMEOUT_SECS ))
  rm -f "$REBUILD_PROMPT_CONFIRM_FILE" "$REBUILD_PROMPT_DISMISS_FILE"
  echo "$deadline" > "$REBUILD_PROMPT_FILE"
  echo "[entrypoint] $(date -Iseconds) rulebook file changed on disk -- offering a rebuild (${REBUILD_PROMPT_TIMEOUT_SECS}s to answer). NOT rebuilding on its own." >> "$BUILD_LOG_FILE"

  while [ "$(date +%s)" -lt "$deadline" ]; do
    if [ -f "$REBUILD_PROMPT_CONFIRM_FILE" ]; then
      rm -f "$REBUILD_PROMPT_FILE" "$REBUILD_PROMPT_CONFIRM_FILE" "$REBUILD_PROMPT_DISMISS_FILE"
      echo "[entrypoint] rebuild confirmed -- rebuilding now." >> "$BUILD_LOG_FILE"
      return 0
    fi
    if [ -f "$REBUILD_PROMPT_DISMISS_FILE" ]; then
      rm -f "$REBUILD_PROMPT_FILE" "$REBUILD_PROMPT_CONFIRM_FILE" "$REBUILD_PROMPT_DISMISS_FILE"
      echo "[entrypoint] rebuild declined -- the running database is left exactly as it is." >> "$BUILD_LOG_FILE"
      return 1
    fi
    sleep 1
  done

  rm -f "$REBUILD_PROMPT_FILE"
  echo "[entrypoint] rebuild offer expired with no answer -- the running database is left exactly as it is." >> "$BUILD_LOG_FILE"
  return 1
}

# Retained for reference only -- the interactive three-way conflict gate that
# check_uncommitted_before_build() used to run. Superseded by save-wins above.
unused_conflict_gate() {
  local base pending
  base="$(basename "$RULEBOOK_PATH" .json)"
  pending=$(ls "$RULEBOOK_DIR"/${base}.uncommitted-*.json 2>/dev/null || true)
  [ -z "$pending" ] && return 0

  # Surface the three-way prompt through the existing boot-server UI (the
  # same page that already shows build progress/logs) instead of proceeding
  # silently. Reuses the existing BOOT_STATE_FILE mechanism with a new state
  # value, and the existing poll-a-fixed-path pattern (like
  # REBUILD_TRIGGER_FILE) for waiting on the user's choice.
  echo "awaiting-conflict-resolution" > "$BOOT_STATE_FILE"
  rm -f "$CONFLICT_CHOICE_FILE"

  echo "[entrypoint] waiting for a conflict-resolution choice via the boot page (or POST /__boot/resolve-conflict)..." >> "$BUILD_LOG_FILE"
  while [ ! -f "$CONFLICT_CHOICE_FILE" ]; do
    sleep 1
  done
  local choice
  choice="$(cat "$CONFLICT_CHOICE_FILE")"
  rm -f "$CONFLICT_CHOICE_FILE"
  echo "[entrypoint] $(date -Iseconds) conflict resolution chosen: $choice" >> "$BUILD_LOG_FILE"

  case "$choice" in
    save-as-unresolved)
      # Option 1 (safe default): move the pending file(s) aside into a single
      # merge-conflict snapshot for later manual/LLM reconciliation, then
      # clear the uncommitted log so the build proceeds on the rulebook file
      # exactly as it currently sits on disk.
      local ts
      ts="$(date +%Y%m%dT%H%M%S)"
      local dest="$RULEBOOK_DIR/${base}.merge-conflict-${ts}.json"
      echo "[entrypoint] saving pending uncommitted change(s) to $dest (unresolved, for later reconciliation)" >> "$BUILD_LOG_FILE"
      {
        echo "{"
        echo "  \"savedAt\": \"$(date -Iseconds)\","
        echo "  \"reason\": \"rulebook changed externally while uncommitted changes were pending\","
        echo "  \"sourceFiles\": ["
        local first=1
        for f in $pending; do
          if [ "$first" -eq 1 ]; then first=0; else echo ","; fi
          printf '    %s' "$(cat "$f")"
        done
        echo ""
        echo "  ]"
        echo "}"
      } > "$dest"
      rm -f $pending
      ;;
    discard)
      # Option 2: throw away the pending log entirely -- equivalent to
      # restarting fresh from whatever the rulebook file currently says.
      echo "[entrypoint] discarding pending uncommitted change(s): $pending" >> "$BUILD_LOG_FILE"
      rm -f $pending
      ;;
    overwrite)
      # Option 3 (not recommended): merge the pending uncommitted log into
      # the rulebook file BEFORE the build runs, so the live-edited version
      # wins over whatever changed the file externally. The actual merge
      # logic (mergeUncommittedIntoRulebook()) lives in the Node API's
      # uncommitted.js -- this is bash, so we do NOT reimplement it here. We
      # call the PREVIOUS API instance's own POST /api/save-changes if it's
      # still up and reachable (start_services() hasn't been re-run yet at
      # this point in the loop, so the process from before this rebuild may
      # still be listening on :5177).
      #
      # KNOWN LIMITATION: this only works while the previous API process is
      # still alive and reachable. If it already died/was killed (e.g. this
      # gate is reached from a path where stop_services() already ran, or on
      # first-boot-after-crash), there is no live merge endpoint to call, and
      # this falls back to the safe "save-as-unresolved" behavior instead of
      # silently doing nothing.
      if curl -sf "http://127.0.0.1:${API_PORT}/api/health" >/dev/null 2>&1; then
        echo "[entrypoint] previous API instance still reachable on :${API_PORT} -- calling POST /api/save-changes to merge uncommitted changes into the rulebook file..." >> "$BUILD_LOG_FILE"
        curl -sf -X POST "http://127.0.0.1:${API_PORT}/api/save-changes" >> "$BUILD_LOG_FILE" 2>&1 || \
          echo "[entrypoint] WARNING: POST /api/save-changes failed -- rulebook file was NOT overwritten with uncommitted changes" >> "$BUILD_LOG_FILE"
      else
        echo "[entrypoint] WARNING: previous API instance is not reachable on :${API_PORT} -- cannot merge via /api/save-changes." >> "$BUILD_LOG_FILE"
        echo "[entrypoint]          falling back to 'save-as-unresolved' so no data is silently lost."  >> "$BUILD_LOG_FILE"
        local ts2
        ts2="$(date +%Y%m%dT%H%M%S)"
        local dest2="$RULEBOOK_DIR/${base}.merge-conflict-${ts2}.json"
        {
          echo "{"
          echo "  \"savedAt\": \"$(date -Iseconds)\","
          echo "  \"reason\": \"overwrite was chosen but the previous API instance was not reachable\","
          echo "  \"sourceFiles\": ["
          local first2=1
          for f in $pending; do
            if [ "$first2" -eq 1 ]; then first2=0; else echo ","; fi
            printf '    %s' "$(cat "$f")"
          done
          echo ""
          echo "  ]"
          echo "}"
        } > "$dest2"
      fi
      rm -f $pending
      ;;
    *)
      echo "[entrypoint] WARNING: unrecognized conflict-resolution choice '$choice' -- treating as 'save-as-unresolved'" >> "$BUILD_LOG_FILE"
      local ts3
      ts3="$(date +%Y%m%dT%H%M%S)"
      cat $pending > "$RULEBOOK_DIR/${base}.merge-conflict-${ts3}.json" 2>/dev/null || true
      rm -f $pending
      ;;
  esac
}

run_build() {
  echo "building" > "$BOOT_STATE_FILE"
  echo "[entrypoint] $(date -Iseconds) running effortless build..." > "$BUILD_LOG_FILE"
  # A stale errors.json from the PREVIOUS build must not be mistaken for this
  # build's result. The CLI removes it itself on a clean build, but only once it
  # gets that far -- if the CLI never runs (or dies before finishing), the old
  # file would still be sitting there describing failures that may already be
  # fixed. Clearing it up front makes "errors.json exists" mean exactly one
  # thing: THIS build produced failures.
  rm -f "$ERRORS_JSON_PATH" "$BOOT_ERRORS_FILE"
  # The registered chmodinitdb step makes the generated reset script
  # executable before initdb runs the compatibility selector. On the first
  # build the selected script does not exist until the preceding
  # rulebooktopostgres step creates it in this same `effortless build` run.
  #
  # -continueOnError is the WHOLE REASON this container survives a broken
  # transpiler. Without it, one failing step (historically rulebook-to-xlsx,
  # a non-load-bearing export step) aborted `effortless build` outright, so
  # the API and admin portal -- which had already generated fine, or would
  # have generated fine from the steps after the failure -- never got built
  # or started, and the container was 100% useless because of a spreadsheet.
  # With the flag: every remaining step still runs, the full exception detail
  # of anything that failed lands in effortless-root/errors.json (served to
  # the boot page as /__boot/errors), and the CLI exits 0. The build result is
  # then judged HERE, by what actually got generated, not by an exit code.
  #
  # This is deliberately ALWAYS ON for this container and is not configurable:
  # a rulebook editor whose job is to help you diagnose a rulebook is worth
  # far more running-with-one-broken-tab than not running at all.
  #
  # Output still goes to the fixed build-log file (boot-server.js tails this
  # file, so its name must stay stable across rebuilds -- NOT timestamped),
  # and is still scanned for the CLI's own "ERROR:" / "TRANSPILER ERROR"
  # markers so the log carries a short, unambiguous summary of which step
  # failed and why.
  #
  # `effortless build` alone does NOT re-resolve `[latest]` for already-
  # pinned transpilers -- effortless.json caches each step's LastUrl /
  # LastVersionUsed from the last time it ran, so a newly published tool
  # version sits unused until something re-pins it. `-upgradeAll` is the
  # documented, project-scoped command for exactly this: it walks every
  # registered ProjectTranspiler and updates its pinned version/URL to the
  # current head, so this rebuild (and every rebuild after it) always
  # consumes whatever is actually live, not a stale build-time snapshot.
  # Runs every time, not just the first build, since a tool can be
  # (re)published at any point while this container is up.
  echo "[entrypoint] $(date -Iseconds) running effortless -upgradeAll to pick up any newly published tool versions..." >> "$BUILD_LOG_FILE"
  # `|| true`: refreshing the tools index is a nice-to-have, not a prerequisite.
  # If the tools server is unreachable (offline laptop, DNS blip, expired token)
  # the build must still run against whatever versions are already pinned --
  # exactly the same "degrade, don't die" rule the build itself now follows.
  (cd /app/effortless-root && effortless -upgradeAll) >> >(tee -a "$BUILD_LOG_FILE") 2>&1 || \
    echo "[entrypoint] WARNING: -upgradeAll failed (tools index not refreshed) -- building with the currently pinned versions." >> "$BUILD_LOG_FILE"
  (cd /app/effortless-root && effortless build $CONTINUE_ON_ERROR_FLAG) >> >(tee -a "$BUILD_LOG_FILE") 2>&1
  build_status=$?
  echo "[entrypoint] $(date -Iseconds) effortless build finished (exit $build_status)" >> "$BUILD_LOG_FILE"

  # errors.json is the CLI's structured record of what failed (see BuildErrorLog
  # in the effortless CLI). Present == this build had failures; absent == clean.
  # Copy it to a fixed path boot-server.js can serve without needing to know
  # where effortless-root resolved to.
  BUILD_HAD_FAILURES=""
  if [ -f "$ERRORS_JSON_PATH" ]; then
    cp "$ERRORS_JSON_PATH" "$BOOT_ERRORS_FILE" 2>/dev/null || true
    BUILD_HAD_FAILURES=1
  fi

  # Fallback for the case where the CLI died before it could write errors.json
  # at all (it crashed, or was killed). The log-scraping heuristic below is
  # strictly a backstop -- errors.json above is the authoritative signal.
  failed_steps=$(grep -B2 "^ERROR:" "$BUILD_LOG_FILE" | grep -oE "\*\*\*\* /[a-zA-Z0-9_/-]+: [a-zA-Z0-9_-]+ \*\*\*\*" | sort -u)
  error_lines=$(grep -E "^ERROR:|TRANSPILER ERROR|Failed to connect to transpiler" "$BUILD_LOG_FILE")
  if [ -z "$BUILD_HAD_FAILURES" ] && [ -n "$error_lines" ]; then
    BUILD_HAD_FAILURES=1
  fi

  if [ -n "$BUILD_HAD_FAILURES" ]; then
    {
      echo ""
      echo "############################################################"
      echo "[entrypoint] BUILD HAD FAILURES -- but the build was NOT aborted."
      echo "[entrypoint] Every remaining step still ran. Whatever generated"
      echo "[entrypoint] successfully will still be started below."
      if [ -f "$BOOT_ERRORS_FILE" ]; then
        echo "[entrypoint] structured detail: $ERRORS_JSON_PATH (also at GET /__boot/errors)"
        echo "[entrypoint] failed step(s):"
        # Node (already in this image) rather than grep/sed over JSON: the field
        # we want is nested, and a regex over a pretty-printed document would
        # just as happily match the `name` of a step that SUCCEEDED.
        node -e '
          const r = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
          for (const e of (r.errors || [])) {
            console.log("[entrypoint]   " + e.name + " (" + (e.relativePath || "") + ")");
            console.log("[entrypoint]     " + (e.message || "(no message reported)"));
          }
        ' "$BOOT_ERRORS_FILE" 2>/dev/null || echo "[entrypoint]   (could not parse $BOOT_ERRORS_FILE)"
      elif [ -n "$failed_steps" ]; then
        echo "[entrypoint] failed step(s):"
        echo "$failed_steps" | sed 's/^/[entrypoint]   /'
      fi
      if [ -n "$error_lines" ]; then
        echo "[entrypoint] error line(s):"
        echo "$error_lines" | sed 's/^/[entrypoint]   /'
      fi
      echo "[entrypoint] full log: $BUILD_LOG_FILE"
      echo "############################################################"
      echo ""
    } >> "$BUILD_LOG_FILE"
  fi
  # NOTE: BOOT_STATE_FILE is deliberately NOT set to "error" here any more.
  # A failed step says nothing about whether the app can run -- that is decided
  # in start_services(), by what actually exists on disk and comes up.
}

start_services() {
  # DEGRADED-BY-DESIGN. This function used to bail out entirely when the build
  # reported any failure, which meant a broken NON-load-bearing step (the XLSX
  # export) took down Postgres-backed browsing, the API, and the portal along
  # with it -- the container became worthless over a spreadsheet.
  #
  # The rule now: start every component that actually exists, independently,
  # and judge readiness by what came up rather than by whether the build was
  # perfect. Each of the three load-bearing pieces is useful on its own:
  #   - Postgres alone: the DB is inspectable from the host on the published port.
  #   - + API: exposes health, state, logs, and the DB's contents for debugging.
  #   - + portal: the last thing to go down, and the piece that can report on
  #     everything BELOW it (whether it can reach the API, which endpoints
  #     answer, what the build errors were).
  # Only if the portal itself cannot start does the boot page take over, and
  # even then it shows the failure rather than a blank screen.
  API_PID=""
  UI_PID=""

  if [ ! -f /app/effortless-root/api/index.js ]; then
    echo "[entrypoint] SKIPPING API start -- /app/effortless-root/api/index.js was not generated (rulebook-to-node-postgres-api did not produce expected output)." >> "$BUILD_LOG_FILE"
  else
    echo "[entrypoint] starting generated Node API (port 5177)..." >> "$BUILD_LOG_FILE"
    # setsid makes this chain (and everything npm/node fork under it) its own
    # process-group leader, so stop_services can kill the WHOLE group with
    # `kill -- -$PID` -- killing just $! (the setsid wrapper's own PID) would
    # leave the real node process it exec's into still running, which is
    # exactly the bug that let old Vite/API servers survive rebuilds and pile
    # up on the same ports.
    # BUILD_LOG_FILE is exported into the API process's own environment (not
    # just this entrypoint's) so routes like /api/save-changes can append
    # their own progress lines (merge steps, applied/SKIPPED changes) into
    # the SAME log boot-server.js already tails over SSE -- otherwise that
    # logging only reaches /tmp/api.log below, which the boot page never
    # shows.
    BUILD_LOG_FILE="$BUILD_LOG_FILE" setsid bash -c 'cd /app/effortless-root/api && npm install --omit=dev --silent && PORT=5177 exec node index.js' \
      > /tmp/api.log 2>&1 &
    API_PID=$!
  fi

  if [ ! -d /app/effortless-root/admin-portal ]; then
    # The portal is the last thing we want to lose, so losing it is the one case
    # that keeps the boot page in front of the user -- with the build log and
    # /__boot/errors right there, which is strictly more than a dead tab.
    {
      echo "[entrypoint] SKIPPING UI start -- /app/effortless-root/admin-portal was not generated (rulebook-to-vite-admin-portal did not produce expected output)."
      echo "[entrypoint] The boot page stays up on :5174 with the build log and, if the build reported failures, GET /__boot/errors."
      if [ -n "$API_PID" ]; then
        echo "[entrypoint] The generated API IS running on :5177 -- reachable from the host for debugging even without the portal."
      fi
    } >> "$BUILD_LOG_FILE"
    write_status_json "error"
    echo "error" > "$BOOT_STATE_FILE"
    return 0
  fi

  # The portal loads the explainer-dag assets from its own publicDir, so a
  # missing folder is not a cosmetic gap -- every derived cell loses its ƒ
  # badge and the Provenance tab has nothing to render. Say so in the build
  # log rather than letting it look like the portal decided not to show them.
  if [ ! -d /app/effortless-root/admin-portal/public/rulebook-explainer-dag ]; then
    echo "[entrypoint] WARNING: admin-portal/public/rulebook-explainer-dag is missing -- the rulebooktoexplainerdag step did not produce output. The portal will report the Provenance tab as not built."  >> "$BUILD_LOG_FILE"
  fi

  echo "[entrypoint] starting generated Vite UI (internal port 5175, dev server)..." >> "$BUILD_LOG_FILE"
  # `vite dev --host` (not `vite build` + a static server) for v1: this repo
  # already runs its own file-watch/rebuild loop at the rulebook level, so a
  # live dev server that also hot-reloads the generated frontend files
  # themselves (in case a future version regenerates UI source shape, not
  # just data) is simpler to keep correct than wiring a second static-file
  # server + manual rebuild step. Bound to the INTERNAL port 5175 --
  # boot-server.js owns the EXTERNAL port 5174 and proxies to this once ready.
  setsid bash -c 'cd /app/effortless-root/admin-portal && npm install --silent && API_PROXY_TARGET=http://127.0.0.1:5177 exec npx vite --host 0.0.0.0 --port 5175' \
    > /tmp/ui.log 2>&1 &
  UI_PID=$!

  echo "[entrypoint] waiting for internal Vite UI to accept connections..."  >> "$BUILD_LOG_FILE"
  UI_UP=""
  for i in $(seq 1 60); do
    if curl -sf "http://127.0.0.1:5175/" >/dev/null 2>&1; then UI_UP=1; break; fi
    sleep 1
  done

  if [ -z "$UI_UP" ]; then
    # The portal directory existed but the dev server never answered (npm install
    # failed, a syntax error in generated code, port already held). Same rule as
    # above: keep the boot page in front of the user so they see WHY.
    {
      echo "[entrypoint] the generated Vite UI did not answer on :5175 within 60s -- see /tmp/ui.log inside the container."
      echo "[entrypoint] Keeping the boot page on :5174 so the log and /__boot/errors stay reachable."
    } >> "$BUILD_LOG_FILE"
    write_status_json "error"
    echo "error" > "$BOOT_STATE_FILE"
    return 0
  fi

  # 'degraded' means: the app is up and fully proxied (identical to 'ready' as
  # far as serving goes), but this build had at least one failed step, so some
  # tab in it will be missing data. It is a SEPARATE state from 'ready' purely so
  # the failure is visible instead of silent -- boot-server.js proxies on both,
  # and the portal can surface a banner off /__boot/status. Reporting 'ready'
  # after a partial failure is exactly the silent-error behavior being fixed here.
  if [ -n "${BUILD_HAD_FAILURES:-}" ]; then
    echo "[entrypoint] app is UP but this build had failed step(s) -- state=degraded. See GET /__boot/errors." >> "$BUILD_LOG_FILE"
    write_status_json "degraded"
    echo "degraded" > "$BOOT_STATE_FILE"
  else
    write_status_json "ready"
    echo "ready" > "$BOOT_STATE_FILE"
  fi
}

# A single machine-readable snapshot of what is actually running, written after
# every build so nothing has to be inferred from log scraping. boot-server.js
# serves this verbatim at GET /__boot/status, which is what lets the portal (or
# a human with curl) answer "which pieces of this container are alive?" even
# when most of them are not.
write_status_json() {
  local state="$1"
  local pg="down" api="down" ui="down" failed="false"
  su postgres -c "psql -c 'select 1' >/dev/null 2>&1" && pg="up"
  curl -sf "http://127.0.0.1:${API_PORT}/api/health" >/dev/null 2>&1 && api="up"
  curl -sf "http://127.0.0.1:5175/" >/dev/null 2>&1 && ui="up"
  [ -n "${BUILD_HAD_FAILURES:-}" ] && failed="true"
  # Which version of each generator tool actually produced what's running --
  # read from the SAME effortless.json readPipeline() already parses, so both
  # surfaces (the step rail and these tiles) always agree. Node (already in
  # this image) rather than grep/sed, for the same nested-JSON reason as the
  # failed-step summary above: a regex over the file could match a DIFFERENT
  # step's LastVersionUsed value.
  local versions
  versions="$(node -e '
    let r = { postgres: null, api: null, portal: null };
    try {
      const cfg = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
      const byName = {};
      for (const t of (cfg.ProjectTranspilers || [])) byName[t.Name] = t.LastVersionUsed || null;
      r = {
        postgres: byName.rulebooktopostgres || null,
        api: byName.rulebooktonodepostgresapi || null,
        portal: byName.rulebooktoviteadminportal || null,
      };
    } catch {}
    console.log(JSON.stringify(r));
  ' "$BOOT_PIPELINE_FILE" 2>/dev/null)"
  [ -z "$versions" ] && versions='{"postgres":null,"api":null,"portal":null}'
  local pg_version api_version portal_version
  pg_version="$(echo "$versions" | node -e 'console.log(JSON.parse(require("fs").readFileSync(0,"utf8")).postgres || "")')"
  api_version="$(echo "$versions" | node -e 'console.log(JSON.parse(require("fs").readFileSync(0,"utf8")).api || "")')"
  portal_version="$(echo "$versions" | node -e 'console.log(JSON.parse(require("fs").readFileSync(0,"utf8")).portal || "")')"
  cat > "$BOOT_STATUS_FILE" <<EOF
{
  "state": "$state",
  "checkedAt": "$(date -Iseconds)",
  "buildHadFailures": $failed,
  "components": {
    "postgres": { "status": "$pg", "note": "in-container cluster; the launcher prints its resolved host port", "version": $([ -n "$pg_version" ] && echo "\"$pg_version\"" || echo null) },
    "api":      { "status": "$api", "note": "generated Node API on container :5177; the launcher prints its resolved host port", "version": $([ -n "$api_version" ] && echo "\"$api_version\"" || echo null) },
    "portal":   { "status": "$ui", "note": "generated Vite UI on internal :5175, proxied through the current browser URL", "version": $([ -n "$portal_version" ] && echo "\"$portal_version\"" || echo null) },
    "bootServer": { "status": "up", "note": "owns the published UI port for the container's whole lifetime" }
  },
  "errorsUrl": "/__boot/errors",
  "logUrl": "/__boot/log"
}
EOF
}

stop_services() {
  echo "[entrypoint] stopping API (pid $API_PID) and UI (pid $UI_PID)..."
  # setsid made API_PID/UI_PID each the leader of their own process group, so
  # `kill -- -$PID` (negative PID = kill the whole group) reaches npm AND the
  # node/vite process it exec'd into -- not just the setsid wrapper itself.
  [ -n "$API_PID" ] && kill -- "-$API_PID" 2>/dev/null
  [ -n "$UI_PID" ] && kill -- "-$UI_PID" 2>/dev/null
  # fuser is a backstop, not the primary mechanism, in case something outside
  # these two process groups is still bound to the ports.
  fuser -k 5177/tcp 2>/dev/null || true
  fuser -k 5175/tcp 2>/dev/null || true
  sleep 1
}

run_build
start_services

# Readiness is reported per COMPONENT, not as one all-or-nothing verdict. A build
# failure no longer implies "nothing is running" -- that conflation is precisely
# what made a broken export step look like a dead container.
report_ready_state() {
  local state
  state="$(cat "$BOOT_STATE_FILE" 2>/dev/null || echo unknown)"
  echo "[entrypoint] READY STATE: $state"
  echo "[entrypoint]   postgres: $(su postgres -c "psql -c 'select 1' >/dev/null 2>&1" && echo up || echo DOWN)"
  echo "[entrypoint]   api:      $([ -n "${API_PID:-}" ] && echo "launched (internal :5177; see launcher output for host port)" || echo "NOT RUNNING (see SKIPPING lines above / /tmp/api.log)")"
  echo "[entrypoint]   portal:   $([ -n "${UI_PID:-}" ] && echo "launched (internal :5175, proxied through the published UI port)" || echo "NOT RUNNING (see SKIPPING lines above / /tmp/ui.log)")"
  echo "[entrypoint]   bootpage: up (published UI port; /__boot/log, /__boot/status, /__boot/errors)"
  if [ -n "${BUILD_HAD_FAILURES:-}" ]; then
    echo "[entrypoint]   NOTE: this build had failed step(s). Everything above that says 'launched' is still fully usable;"
    echo "[entrypoint]         only the output of the failed step(s) is missing. Details: GET /__boot/errors"
  fi
  echo "[entrypoint]   (npm install still running in the background may delay a first response by 10-30s.)"
}
report_ready_state

echo "[entrypoint] watching $RULEBOOK_PATH and $REBUILD_TRIGGER_FILE for changes (Ctrl-C / docker stop to exit)..."
while true; do
  # No stale offer may survive into the next wait: an answer file left behind
  # from a previous round would auto-confirm the next prompt.
  rm -f "$REBUILD_PROMPT_FILE" "$REBUILD_PROMPT_CONFIRM_FILE" "$REBUILD_PROMPT_DISMISS_FILE"

  # Watch the rulebook's DIRECTORY, not the rulebook file itself.
  #
  # inotify watches an INODE. A file watched by path is only followed as long as
  # that inode keeps its name -- and the single most common way a rulebook gets
  # saved does not preserve it. Editors that save atomically (write temp, rename
  # over), `git checkout`, `git stash`, `mv` all REPLACE the file. Watching the
  # file directly then fails in two separate ways, both of which were live bugs:
  # the pending wait sits forever on an inode nobody can reach any more (the
  # edit is silently MISSED), and the next setup fails outright (which used to
  # take the whole container down as a FATAL "lost its bind mount").
  #
  # A directory watch has neither problem: the directory keeps its identity, and
  # a replace shows up as a plain create/moved_to event naming the file. The
  # FATAL branch below then means what it always claimed to mean -- the mount is
  # actually gone -- instead of firing on an ordinary save.
  #
  # The cost is that the directory holds other files this loop must NOT react
  # to: the uncommitted-change log and the editor-settings file, both written by
  # the API itself. So events are filtered by name below, and anything else is
  # ignored without so much as a prompt.
  if ! inotifywait -e modify -e close_write -e move -e create "$RULEBOOK_DIR" "$REBUILD_TRIGGER_FILE" >/tmp/watch.log 2>&1; then
    # inotifywait only returns non-zero when it failed to SET UP the watch --
    # never on a real event, which always exits 0. Treating a setup failure as
    # an event is what once caused an infinite instant-rebuild loop: the watch
    # would fail instantly, get logged as "change detected", rebuild, re-enter
    # the loop, fail instantly again, forever. Fail loudly and stop instead.
    echo "[entrypoint] FATAL: inotifywait failed -- this is an error watching the path(s) below, NOT a detected file change:" >&2
    cat /tmp/watch.log >&2
    {
      echo ""
      echo "############################################################"
      echo "[entrypoint] FATAL: $(date -Iseconds) file watcher failed -- see below. Stopping instead of retry-looping."
      cat /tmp/watch.log | sed 's/^/[entrypoint]   /'
      echo "[entrypoint] This almost always means $RULEBOOK_DIR lost its bind mount (host path missing/wrong)."
      echo "############################################################"
      echo ""
    } >> "$BUILD_LOG_FILE"
    echo "error" > "$BOOT_STATE_FILE"
    stop_services
    exit 1
  fi

  # Which file actually moved? A directory watch reports every file in there,
  # and most of them are the API's own bookkeeping (the uncommitted-change log,
  # the editor-settings file) that must never trigger anything.
  RULEBOOK_BASENAME="$(basename "$RULEBOOK_PATH")"
  if ! grep -q "$REBUILD_TRIGGER_FILE" /tmp/watch.log 2>/dev/null \
     && ! grep -q "$RULEBOOK_BASENAME" /tmp/watch.log 2>/dev/null; then
    continue
  fi

  # Two very different reasons to be here, handled differently on purpose.
  if grep -q "$REBUILD_TRIGGER_FILE" /tmp/watch.log 2>/dev/null; then
    # The Rebuild button (or POST /__boot/rebuild) -- somebody asked for this
    # in so many words, so there is nothing to ask about.
    echo "[entrypoint] $(date -Iseconds) rebuild requested explicitly -- rebuilding..."
  else
    # The rulebook FILE changed. If the app itself just wrote it (Save, or an
    # auto-save), there is nothing to ask: Postgres already matches what was
    # written, so a rebuild would be pure churn.
    now_epoch=$(date +%s)
    self_write_epoch=$(cat "$SELF_WRITE_MARKER_FILE" 2>/dev/null || echo 0)
    case "$self_write_epoch" in (''|*[!0-9]*) self_write_epoch=0 ;; esac
    if [ "$(( now_epoch - self_write_epoch ))" -le "$SELF_WRITE_GRACE_SECS" ]; then
      echo "[entrypoint] $(date -Iseconds) rulebook file changed by our own Save -- Postgres already matches it, so no rebuild is offered." >> "$BUILD_LOG_FILE"
      continue
    fi

    # A genuine outside change (hand-edited, or written by another process). A
    # rebuild no longer drops the database -- it adds tables/columns and
    # upserts rulebook rows (see run-rulebook-db-reset.sh) -- but it still
    # takes the API and portal down for the duration, and it still pushes the
    # rulebook's own values over any edits made here to the same rows. Enough
    # to be worth asking about rather than doing. No answer within the timeout
    # means no rebuild.
    if ! prompt_for_rebuild; then
      continue
    fi
  fi

  # Every build from here on is gated on pending uncommitted changes -- the
  # FIRST build above (before this loop) is deliberately NOT gated, since
  # nothing can be pending yet at container boot.
  check_uncommitted_before_build
  stop_services
  run_build
  start_services
  report_ready_state
done
