#!/bin/bash
# edit-rulebook.sh -- GENERATED by effortless-rulebook-editor.
#
# Dockerfile and its sibling files (container-entrypoint.sh, boot-server.js,
# effortless.editor.json) live at docker/Dockerfile relative to THIS script's
# own folder.
#
# Host ports are assigned by Docker unless pinned with RULEBOOK_EDITOR_*_PORT
# variables or a ports.env file beside this launcher.
#
# Refresh your browser after editing effortless-rulebook.json -- the container's
# filesystem watcher detects the change, re-runs `effortless build`, and
# restarts the API + UI automatically.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

DOCKERFILE_PATH="docker/Dockerfile"
EXTERNAL_SRC_MOUNTED=
EXTERNAL_SRC_HOST_PATH=""
RULEBOOK_SELF_UPDATE_PATH="effortless-rulebook.json"
EDITOR_RUNTIME_VERSION="2026.9.17.2059"

# The launcher is the OUTER half of the editor and therefore cannot rely on the
# container's inner `effortless -upgradeAll`. Update and regenerate this runtime
# from the published head before Docker starts, then re-exec the newly written
# launcher exactly once. This makes "stop it and start it again" sufficient to
# pick up both editor fixes and inner pipeline-tool updates.
if [ "${EFFORTLESS_EDITOR_LAUNCHER_CURRENT:-}" != "1" ]; then
  if ! command -v effortless >/dev/null 2>&1; then
    echo "ERROR: the effortless CLI is required to update the rulebook editor before launch." >&2
    exit 1
  fi
  echo "Updating effortless-rulebook-editor to the published head..."
  effortless effortless-rulebook-editor -upgrade

  PROJECT_SEARCH_DIR="$(pwd -P)"
  PROJECT_FILE=""
  while [ "$PROJECT_SEARCH_DIR" != "/" ]; do
    if [ -f "$PROJECT_SEARCH_DIR/effortless.json" ]; then
      PROJECT_FILE="$PROJECT_SEARCH_DIR/effortless.json"
      break
    fi
    PROJECT_SEARCH_DIR="$(dirname "$PROJECT_SEARCH_DIR")"
  done
  if [ -z "$PROJECT_FILE" ]; then
    echo "ERROR: no effortless.json found above $(pwd -P) after editor upgrade." >&2
    exit 1
  fi

  EDITOR_HEAD_INFO="$(node - "$PROJECT_FILE" <<'NODE'
const fs = require('fs');
const cfg = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const steps = Array.isArray(cfg.ProjectTranspilers) ? cfg.ProjectTranspilers : [];
const editor = steps.find((step) => {
  const name = String(step.Name || '').replaceAll('-', '').toLowerCase();
  const command = String(step.CommandLine || '').trim().split(/\s+/)[0];
  return name === 'effortlessrulebookeditor' || command === 'effortless-rulebook-editor';
});
if (!editor) throw new Error('effortless-rulebook-editor is not registered in effortless.json');
const normalized = String(editor.LastVersionUsed || '').replace(/^v/, '')
  .split('.').map((part) => String(Number(part))).join('.');
process.stdout.write(normalized + '\t' + String(editor.LastUrl || ''));
NODE
)"
  IFS=$'\t' read -r EDITOR_HEAD_VERSION EDITOR_HEAD_URL <<< "$EDITOR_HEAD_INFO"

  RUNTIME_COMPLETE=1
  SELF_UPDATE_DOCKER_DIR="$(dirname "$DOCKERFILE_PATH")"
  for REQUIRED_FILE in \
    "$DOCKERFILE_PATH" \
    "$SELF_UPDATE_DOCKER_DIR/container-entrypoint.sh" \
    "$SELF_UPDATE_DOCKER_DIR/boot-server.js" \
    "$SELF_UPDATE_DOCKER_DIR/effortless.editor.json"; do
    [ -f "$REQUIRED_FILE" ] || RUNTIME_COMPLETE=0
  done

  if [ "$EDITOR_HEAD_VERSION" = "$EDITOR_RUNTIME_VERSION" ] && [ "$RUNTIME_COMPLETE" = "1" ]; then
    echo "Editor runtime is current ($EDITOR_RUNTIME_VERSION)."
    export EFFORTLESS_EDITOR_LAUNCHER_CURRENT=1
  else
    if [ -z "$EDITOR_HEAD_URL" ]; then
      echo "ERROR: the published editor version has no resolved LastUrl in $PROJECT_FILE." >&2
      exit 1
    fi
    if ! command -v curl >/dev/null 2>&1; then
      echo "ERROR: curl is required to warm the published editor workload before updating." >&2
      exit 1
    fi
    echo "Warming published editor workload: $EDITOR_HEAD_URL"
    EDITOR_WORKLOAD_READY=""
    for ATTEMPT in $(seq 1 36); do
      if curl --max-time 10 -fsS "$EDITOR_HEAD_URL/healthz" >/dev/null 2>&1; then
        EDITOR_WORKLOAD_READY=1
        break
      fi
      echo "  editor workload not ready ($ATTEMPT/36)..."
      sleep 2
    done
    if [ -z "$EDITOR_WORKLOAD_READY" ]; then
      echo "ERROR: published editor workload did not become ready: $EDITOR_HEAD_URL/healthz" >&2
      exit 1
    fi

    SELF_UPDATE_ARGS=(
      effortless-rulebook-editor
      -i "$RULEBOOK_SELF_UPDATE_PATH"
      -p "rulebookPath=$RULEBOOK_SELF_UPDATE_PATH"
      -p "dockerfilePath=$DOCKERFILE_PATH"
    )
    if [ -n "$EXTERNAL_SRC_MOUNTED" ]; then
      SELF_UPDATE_ARGS+=( -p "pathToExternalSrc=$EXTERNAL_SRC_HOST_PATH" )
    fi
    effortless "${SELF_UPDATE_ARGS[@]}"
    export EFFORTLESS_EDITOR_LAUNCHER_CURRENT=1
    exec bash "$0" "$@"
  fi
fi

# On Windows Git Bash (MSYS), MSYS silently rewrites POSIX-looking paths in
# command arguments before docker.exe ever sees them. Applied blindly to a
# `docker run -v SRC:DST` argument, it mangles the CONTAINER-side path too
# (observed in practice: "/app/effortless-rulebook" became
# "\Program Files\Git\app\effortless-rulebook"), so the rulebook folder never
# actually appears inside the container at all. Disabling MSYS's path
# conversion for the docker commands below and converting the HOST-side path
# ourselves (native Windows path via cygpath) fixes this without affecting
# macOS/Linux, where none of this applies (MSYSTEM is unset there).
if [ -n "${MSYSTEM:-}" ] && command -v cygpath >/dev/null 2>&1; then
  export MSYS_NO_PATHCONV=1
  to_native_path() { cygpath -w "$1"; }
else
  to_native_path() { printf '%s' "$1"; }
fi

# Content-address the image from the generated runtime files that Docker COPYs.
# The old launcher used one machine-global `effortless-rulebook-editor` tag and
# skipped `docker build` whenever that tag existed. Starting project B could
# therefore run project A's older editor image -- including an older boot page --
# with no warning. Different generated runtimes now have different tags; identical
# runtimes may still share Docker's image/cache safely.
DOCKERFILE_DIR="$(dirname "$DOCKERFILE_PATH")"
DOCKERFILE_NAME="$(basename "$DOCKERFILE_PATH")"
IMAGE_FINGERPRINT="$(
  (
    cd "$DOCKERFILE_DIR"
    cksum "$DOCKERFILE_NAME" container-entrypoint.sh boot-server.js effortless.editor.json
  ) | cksum | awk '{print $1}'
)"
IMAGE_NAME="effortless-rulebook-editor:$IMAGE_FINGERPRINT"

# Optional project-local port/name pins. Capture caller-provided values first
# so an explicit environment variable wins over the same key in ports.env.
CALLER_CONTAINER_NAME_SET="${RULEBOOK_EDITOR_CONTAINER_NAME+x}"
CALLER_CONTAINER_NAME="${RULEBOOK_EDITOR_CONTAINER_NAME-}"
CALLER_API_PORT_SET="${RULEBOOK_EDITOR_API_PORT+x}"
CALLER_API_PORT="${RULEBOOK_EDITOR_API_PORT-}"
CALLER_UI_PORT_SET="${RULEBOOK_EDITOR_UI_PORT+x}"
CALLER_UI_PORT="${RULEBOOK_EDITOR_UI_PORT-}"
CALLER_PG_PORT_SET="${RULEBOOK_EDITOR_PG_PORT+x}"
CALLER_PG_PORT="${RULEBOOK_EDITOR_PG_PORT-}"

PORTS_ENV_FILE="${RULEBOOK_EDITOR_PORTS_ENV_FILE:-$(dirname "$0")/ports.env}"
if [ -f "$PORTS_ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$PORTS_ENV_FILE"
fi

[ -n "$CALLER_CONTAINER_NAME_SET" ] && RULEBOOK_EDITOR_CONTAINER_NAME="$CALLER_CONTAINER_NAME"
[ -n "$CALLER_API_PORT_SET" ] && RULEBOOK_EDITOR_API_PORT="$CALLER_API_PORT"
[ -n "$CALLER_UI_PORT_SET" ] && RULEBOOK_EDITOR_UI_PORT="$CALLER_UI_PORT"
[ -n "$CALLER_PG_PORT_SET" ] && RULEBOOK_EDITOR_PG_PORT="$CALLER_PG_PORT"

# A path fingerprint makes the default identity unique even though almost every
# install lives in a folder literally named `effortless-rulebook`. The readable
# slug is diagnostic only; the fingerprint is what prevents same-named projects
# in different parent folders from colliding.
INSTALL_PATH="$(pwd -P)"
INSTALL_SLUG="$(
  printf '%s-%s' "$(basename "$(dirname "$INSTALL_PATH")")" "$(basename "$INSTALL_PATH")" |
    tr '[:upper:]' '[:lower:]' |
    tr -cs 'a-z0-9_.-' '-' |
    awk '{ sub(/^-+/, ""); sub(/-+$/, ""); print }'
)"
INSTALL_FINGERPRINT="$(printf '%s' "$INSTALL_PATH" | cksum | awk '{print $1}')"
CONTAINER_NAME="${RULEBOOK_EDITOR_CONTAINER_NAME:-effortless-rulebook-editor-${INSTALL_SLUG}-${INSTALL_FINGERPRINT}}"

# Empty means Docker chooses a free host port. Projects that need stable URLs
# pin any/all of these in ports.env or the invoking environment.
API_PORT="${RULEBOOK_EDITOR_API_PORT:-}"
UI_PORT="${RULEBOOK_EDITOR_UI_PORT:-}"
PG_PORT="${RULEBOOK_EDITOR_PG_PORT:-}"

validate_port() {
  local label="$1" value="$2"
  [ -z "$value" ] && return 0
  if ! [[ "$value" =~ ^[0-9]+$ ]] || (( 10#$value < 1 || 10#$value > 65535 )); then
    echo "ERROR: $label must be an integer from 1 to 65535; got '$value'." >&2
    exit 1
  fi
}
validate_port RULEBOOK_EDITOR_API_PORT "$API_PORT"
validate_port RULEBOOK_EDITOR_UI_PORT "$UI_PORT"
validate_port RULEBOOK_EDITOR_PG_PORT "$PG_PORT"
if { [ -n "$API_PORT" ] && [ "$API_PORT" = "$UI_PORT" ]; } ||
   { [ -n "$API_PORT" ] && [ "$API_PORT" = "$PG_PORT" ]; } ||
   { [ -n "$UI_PORT" ] && [ "$UI_PORT" = "$PG_PORT" ]; }; then
  echo "ERROR: API, UI, and Postgres host ports must be distinct when pinned." >&2
  exit 1
fi

# Remove only this install's previous container. A launcher must never kill a
# differently named project merely because both requested the same host port.
docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true

# Pinned-port conflicts are configuration failures, not permission to destroy
# another project's container. Fail with the owner names; unpinned ports cannot
# conflict because Docker allocates them.
for PORT in "$API_PORT" "$UI_PORT" "$PG_PORT"; do
  [ -z "$PORT" ] && continue
  CONFLICTING_CIDS="$(docker ps -q --filter "publish=$PORT")"
  if [ -n "$CONFLICTING_CIDS" ]; then
    CONFLICTING_NAMES="$(docker ps --filter "publish=$PORT" --format '{{.Names}}' | tr '\n' ' ')"
    echo "ERROR: requested host port $PORT is already owned by: $CONFLICTING_NAMES" >&2
    echo "Choose another RULEBOOK_EDITOR_*_PORT value; no other container was stopped." >&2
    exit 1
  fi
done

# Build only if the image doesn't exist yet. Run ./edit-rulebook.sh --rebuild
# to force a fresh image build (e.g. after pulling a new Dockerfile).
if [ "${1:-}" = "--rebuild" ] || ! docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
  echo "Building $IMAGE_NAME image..."
  docker build -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" "$DOCKERFILE_DIR"
fi

RULEBOOK_DIR_NATIVE="$(to_native_path "$(pwd)")"
SSOTME_DIR_NATIVE="$(to_native_path "$HOME/.ssotme")"
API_PUBLISH="${API_PORT:+${API_PORT}:}5177"
UI_PUBLISH="${UI_PORT:+${UI_PORT}:}5174"
PG_PUBLISH="${PG_PORT:+${PG_PORT}:}5432"

DOCKER_RUN_ARGS=(
  -d
  --name "$CONTAINER_NAME"
  -p "$API_PUBLISH"
  -p "$UI_PUBLISH"
  -p "$PG_PUBLISH"
  -v "$RULEBOOK_DIR_NATIVE:/app/effortless-rulebook"
  -v "$SSOTME_DIR_NATIVE:/root/.ssotme-ro:ro"
  -e "RULEBOOK_FILENAME=$RULEBOOK_SELF_UPDATE_PATH"
)

# Second bind-mount: only when -p pathToExternalSrc=... was passed at
# generation time. Otherwise the container keeps ALL of its scratch/
# generated-code state purely internal (see container-entrypoint.sh's
# effortless-root symlink target) -- nothing lands on the host, nothing
# needs a .gitignore entry.
if [ -n "$EXTERNAL_SRC_MOUNTED" ]; then
  mkdir -p "$EXTERNAL_SRC_HOST_PATH"
  # .gitignore the whole external-src folder -- it's disposable container
  # scratch state (effortless.json + every generated file), not something
  # to commit.
  if [ ! -f "$EXTERNAL_SRC_HOST_PATH/.gitignore" ]; then
    printf '*\n' > "$EXTERNAL_SRC_HOST_PATH/.gitignore"
  fi
  EXTERNAL_SRC_NATIVE="$(to_native_path "$(cd "$EXTERNAL_SRC_HOST_PATH" && pwd)")"
  DOCKER_RUN_ARGS+=( -v "$EXTERNAL_SRC_NATIVE:/app/effortless-editor-tmp" )
  DOCKER_RUN_ARGS+=( -e "EFFORTLESS_EDITOR_TEMPDIR_MOUNTED=1" )
fi

# Forward the host's Anthropic key into the container so the generated API's
# chat endpoint (POST /api/chat, see chatbot.js) can reach Claude.
#
# Two sources, in order: an `effortless.env` file next to this script, then the
# invoking shell's environment. The file is checked FIRST and matters most --
# relying on the shell alone is fragile, because this script is commonly run
# from an IDE terminal, a GUI launcher, or a non-login shell that never sourced
# ~/.zshrc, and the key then silently is not forwarded (the container starts
# fine and only the chat reports itself unavailable, which is a confusing way
# to discover a missing env var). `effortless.env` is already gitignored by the
# standard effortless .gitignore, so the secret stays out of version control.
#
# The value is passed to docker by NAME (`-e VAR`, no `=value`), so it is never
# written into this script, the image, or any generated file.
ENV_FILE="$(dirname "$0")/effortless.env"
if [ -f "$ENV_FILE" ]; then
  # `set -a` marks everything defined while it is on for export, so a plain
  # `ANTHROPIC_API_KEY=sk-...` line in the file (no `export` keyword needed)
  # still reaches the docker process.
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  DOCKER_RUN_ARGS+=( -e ANTHROPIC_API_KEY )
else
  echo "NOTE: ANTHROPIC_API_KEY is not set, so the admin portal's chat widget"
  echo "      will report itself unavailable. Everything else runs normally."
  echo "      To enable it, create $ENV_FILE containing:"
  echo "          ANTHROPIC_API_KEY=sk-ant-..."
  echo "      (that filename is already gitignored), or export the variable"
  echo "      in the shell you run this script from."
fi

echo "Starting $CONTAINER_NAME container..."
docker run "${DOCKER_RUN_ARGS[@]}" "$IMAGE_NAME"

RESOLVED_API_PORT="$(docker port "$CONTAINER_NAME" 5177/tcp | awk -F: 'NR == 1 { print $NF }')"
RESOLVED_UI_PORT="$(docker port "$CONTAINER_NAME" 5174/tcp | awk -F: 'NR == 1 { print $NF }')"
RESOLVED_PG_PORT="$(docker port "$CONTAINER_NAME" 5432/tcp | awk -F: 'NR == 1 { print $NF }')"

echo ""
echo "effortless-rulebook-editor is starting up."
echo "  CONTAINER: $CONTAINER_NAME"
echo "  API:  http://localhost:$RESOLVED_API_PORT/api/state"
echo "  DOCS: http://localhost:$RESOLVED_API_PORT/api/docs"
echo "                            (START HERE to build an app against this API: every"
echo "                            route, the read-snake_case/write-PascalCase rule, and"
echo "                            pointers to /api/rulespeak + /api/source. Derived from"
echo "                            the live route table, so it cannot go stale.)"
echo "  UI:   http://localhost:$RESOLVED_UI_PORT   (shows a live boot/progress page immediately --"
echo "                            no need to wait before opening it; it hands off"
echo "                            to the real app automatically once ready, and has"
echo "                            its own Rebuild button + log view at any time)"
echo "  PG:   postgresql://postgres:postgres@localhost:$RESOLVED_PG_PORT/effortless-rulebook"
echo "                            (for a host psql client / GUI tool -- this is the"
echo "                            ONLY supported way to inspect data directly. Built"
echo "                            from scratch each time the container starts; while it"
echo "                            runs, a rebuild only adds tables/columns and upserts"
echo "                            the rulebook's own rows)"
echo ""
echo "Edit effortless-rulebook.json to trigger a rebuild -- the container watches"
echo "the file (and the UI's Rebuild button) and rebuilds automatically."
echo ""
echo "Following container logs now (Ctrl-C stops watching logs -- the container keeps running;"
echo "re-run this script, or 'docker logs -f $CONTAINER_NAME', to watch again)..."
echo ""
exec docker logs -f "$CONTAINER_NAME"
